### ISSUE TITLE
Residue reindexing

### ISSUE THREAD

**Issue by salotz** [mdtraj/mdtraj#1020]
I ran into a problem with using the atom.residue.index property as a way to get the residues from the topology after taking a discontinuous atom_slice from the trajectory. This example sums it up:

```
import mdtraj as md
import os.path as osp
import numpy as np
import pandas as pd

topo_path = "path/to/topology.pdb"
t0_path = "/path/to/traj.dcd"

# use a discontinuous slice
test_slice = range(0,3428) + range(40996, 41006)
t0 = md.load(t0_path, top=topo_path)[0].atom_slice(test_slice)

# we see that the index you access a residue by using the residue
# function does not match the index property

print "Access to topology.residue(285) gives you a residue with residue.index:",        t0.top.residue(285).index

# I have an atom I want to get the residue index of the residue it is
# a part of
res_index = t0.top.atom(3428).residue.index
print "topology.atom(3428) according to it's residue.index property is:", res_index

print "So I cannot access that residue from the topology with topology.residue("+str(res_index)+")"

print "And I get an error:"

# and then access that residue, which fails
t0.top.residue(res_index)
```

Output is:
    Access to topology.residue(285) gives you a residue with residue.index: 12807

```
topology.atom(3428) according to it's residue.index property is: 12807

So I cannot access that residue from the topology with topology.residue(12807)

And I get an error:

Traceback (most recent call last):
  File "bug_report.py", line 36, in <module>
    t0.top.residue(res_index)
  File "/usr/local/lib/python2.7/dist-packages/mdtraj/core/topology.py", line 691, in residue
    return self._residues[index]
IndexError: list index out of range
```

The error is because that index is not in the range of residue indices.

My thoughts are that when the atom_slice is run the residue.index property is not properly updated to reflect the actual index used to find it.

**Comment by rmcgibbo** [comment]
(cc: http://discourse.mdtraj.org/t/residue-indexing-questions/125)

**Comment by gph82** [comment]
Hi guys I don't want to open an issue if this behavior is known. Any feedback or comment:
```python
geom = md.load_pdb('http://www.rcsb.org/pdb/files/4ZUO.pdb')
sliced_geom = geom.atom_slice(np.arange(100,200)) # random selection
print(sliced_geom.top._residues[0].index)
# 11
```
But the docs say that residue.index  is ```The index of the Residue within its Topology```, so I am bit confused (after so many years using mdtraj!)
