### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by peastman** [mdtraj/mdtraj#1069]
I'm getting an error when I try to use mdtraj after compiling it from source.  I started from a clean anaconda install, then installed mdtraj with the usual `python setup.py build; python setup.py install`.  Everything seemed to work correctly.  But I get an error when I try to use it:

```
>>> import mdtraj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peastman/workspace/mdtraj/mdtraj/__init__.py", line 29, in <module>
    from mdtraj.formats.registry import FormatRegistry
  File "/home/peastman/workspace/mdtraj/mdtraj/formats/__init__.py", line 2, in <module>
    from mdtraj.formats.dcd import DCDTrajectoryFile
ImportError: cannot import name 'DCDTrajectoryFile'
```

As far as I can tell, everything seems to be installed where it should be.  For example,

```
$ ls ~/anaconda3/lib/python3.5/site-packages/mdtraj-1.7.0.dev0-py3.5-linux-x86_64.egg/mdtraj/formats/
amberrst.py                             dtr.py        mdcrd.py      __pycache__
arc.py                                  gro.py        mol2.py       registry.py
binpos.cpython-35m-x86_64-linux-gnu.so  hdf5.py       netcdf.py     trr.cpython-35m-x86_64-linux-gnu.so
binpos.py                               hoomdxml.py   openmmxml.py  trr.py
dcd.cpython-35m-x86_64-linux-gnu.so     __init__.py   pdb           xtc.cpython-35m-x86_64-linux-gnu.so
dcd.py                                  lammpstrj.py  prmtop.py     xtc.py
dtr.cpython-35m-x86_64-linux-gnu.so     lh5.py        psf.py        xyzfile.py
```

Any idea what's causing this?

**Comment by peastman** [comment]
Never mind, I see the problem!  I was in the mdtraj directory when I launched Python.  Hence, it interpreted `mdtraj` as the local directory rather than the installed package.  Sigh...
