### ISSUE TITLE
top.selection cannot handle residue names starting with a number.

### ISSUE THREAD

**Issue by JoaoRodrigues** [mdtraj/mdtraj#1126]
Hi there,

The title says it all. Trying to make a selection of a residue name starting with a number, e.g. 1AA, fails with the following error:

```
Traceback (most recent call last):
  File "../../../scripts/calc_ligand_contacts.py", line 48, in <module>
    ligand_atoms = trj.top.select('resname {0!s}'.format(cline_args.ligand))
  File "/Users/joao/software/mdtraj/build/lib.macosx-10.11-intel-2.7/mdtraj/core/topology.py", line 934, in select
    filter_func = parse_selection(selection_string).expr
  File "/Users/joao/software/mdtraj/build/lib.macosx-10.11-intel-2.7/mdtraj/core/selection.py", line 354, in __call__
    raise ValueError('\n'.join(lines))
ValueError: Expected end of text (at char 9), (line:1, col:10): resname 1AA
```

I tried digging around in the parse_selection code, but I can't figure out where the rule to parse the literal name is. Residue names A1A, AA1, all work, so this is very specific to this case.

**Comment by rmcgibbo** [comment]
Thanks for the report. This probably just requires a small tweak to the grammar.

**Comment by JoaoRodrigues** [comment]
Thanks! I figured out that much, just don't know where to look.. If you
point me to where this part is defined I can give it a try.

A qui, 9/06/2016, 21:34, Robert T. McGibbon <notifications@github.com>
escreveu:

**Comment by rmcgibbo** [comment]
I think it might be this line https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/selection.py#L307

**Comment by JoaoRodrigues** [comment]
Got it past that error by removing `Word(NUMS)` or moving it to the end of the expression, but I hit another error:

```
Traceback (most recent call last):
  File "../../../scripts/calc_ligand_contacts.py", line 48, in <module>
    ligand_atoms = trj.top.select('resname {0!s}'.format(cline_args.ligand))
  File "/Users/joao/software/mdtraj/build/lib.macosx-10.11-intel-2.7/mdtraj/core/topology.py", line 933, in select
    filter_func = parse_selection(selection_string).expr
  File "/Users/joao/software/mdtraj/build/lib.macosx-10.11-intel-2.7/mdtraj/core/selection.py", line 362, in __call__
    astnode = self.transformer.visit(deepcopy(parse_result[0].ast()))
  File "/Users/joao/software/mdtraj/build/lib.macosx-10.11-intel-2.7/mdtraj/core/selection.py", line 241, in ast
    comparators=[e.ast() for e in self.comparators[1:]])
  File "/Users/joao/software/mdtraj/build/lib.macosx-10.11-intel-2.7/mdtraj/core/selection.py", line 147, in ast
    return ast.parse(self.token, mode='eval').body
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    1AA
```

I'll leave it to the experts, way out of my depth here :-)

**Comment by mpharrigan** [comment]
Does it work if you surround it in quotes?

**Comment by JoaoRodrigues** [comment]
@mpharrigan It does! Not very intuitive though..

**Comment by rmcgibbo** [comment]
Ahh, the reason for the transform problem is that the code relies on the resnames being valid python identifiers, so you might be out of luck, other than the quote solution.
