### ISSUE TITLE
'LinAlgError: Singular matrix' Dihedral Featurizer error on msmbuilder

### ISSUE THREAD

**Issue by jeiros** [mdtraj/mdtraj#1131]
Hi there, 

I opened some days ago an [issue](https://github.com/msmbuilder/msmbuilder/issues/819) in the msmbuilder package but was told to open an issue here as it seems to originate from mdtraj.

Thanks for any input 😄

**Comment by jeiros** [comment]
Hello

I had forgotten about this issue until I recently tried to automate the cross validation procedure using [osprey](https://github.com/msmbuilder/osprey).

The estimator I'm using in osprey is msmbuilder, here is the [config.yaml](http://lpaste.net/7292557798036996096) file I'm using.

I am getting the same Singular matrix error when trying to analyze a system that has two phosphorylated serines using a Dihedral Featurizer. I've tried changing the resname of the phosphorylated serines from S1P to SER again, but still no success. I think it might be related to MDtraj not being able to find the dihedrals for those residues? (I think they are the problem because the analysis works fine for the same protein with standard residues)

I'm pasting as well the error traceback that I'm getting from osprey:
```
----------------------------------------------------------------------
Beginning iteration                                             2 / 10
----------------------------------------------------------------------
Loading trials database: sqlite:///osprey-trials.db...
History contains: 1 trials
Choosing next hyperparameters with random...
  {'msm__lag_time': 9, 'tica__n_components': 1, 'tica__lag_time': 5, 'featurizer__types': ['chi1', 'chi2'], 'cluster__n_clusters': 9, 'msm__n_timescales': 5}
(random took 0.000 s)

/Users/je714/anaconda3/lib/python3.5/site-packages/mdtraj/geometry/dihedral.py:118: UserWarning: Optimized dihedral calculation does not work for non-orthorhombic unit cells and periodic boundary conditions. Falling back to much slower pure-Python implementation. Set periodic=False or opt=False to disable this message.
  warnings.warn('Optimized dihedral calculation does not work for non-orthorhombic '
Loading trials database: sqlite:///osprey-trials.db...
------------------------------------------------------------------------------
Exception encountered while fitting model
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/osprey/execute_worker.py", line 132, in run_single_trial
    estimator, params, cv=cv, scoring=scoring, X=X, y=y, verbose=1)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/osprey/fit_estimator.py", line 59, in fit_and_score_estimator
    for train, test in cv)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 72, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/osprey/fit_estimator.py", line 129, in _fit_and_score
    estimator.fit(X_train, **fit_params)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py", line 164, in fit
    Xt, fit_params = self._pre_transform(X, y, **fit_params)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py", line 145, in _pre_transform
    Xt = transform.fit_transform(Xt, y, **fit_params_steps[name])
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/base.py", line 455, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/msmbuilder/featurizer/featurizer.py", line 159, in transform
    return [self.partial_transform(traj) for traj in traj_list]
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/msmbuilder/featurizer/featurizer.py", line 159, in <listcomp>
    return [self.partial_transform(traj) for traj in traj_list]
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/msmbuilder/featurizer/featurizer.py", line 501, in partial_transform
    _, y = func(traj)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/mdtraj/geometry/dihedral.py", line 529, in compute_chi1
    all_chi = compute_dihedrals(traj, indices, periodic=periodic, opt=opt)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/mdtraj/geometry/dihedral.py", line 131, in compute_dihedrals
    _dihedral(traj, quartets, periodic, out)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/mdtraj/geometry/dihedral.py", line 68, in _dihedral
    b1 = distance.compute_displacements(traj, ix10, periodic=periodic, opt=False)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/mdtraj/geometry/distance.py", line 131, in compute_displacements
    return _displacement_mic(xyz, pairs, box.transpose(0, 2, 1), orthogonal)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/mdtraj/geometry/distance.py", line 227, in _displacement_mic
    hinv = np.linalg.inv(box_vectors[i])
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 526, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/Users/je714/anaconda3/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```
I'm getting the same LinAlgError for all the trials by the osprey worker (changing the dihedral types, for example).
I'm tagging @rmcgibbo and @cxhernandez because this is kind of old issue and I don't know if it's going to be bumped up to the top when I post this reply to myself. 
Again, any comments on this (or directions on things to tweak if this is something that I could fix and do a PR on) will be greatly appreciated.

**Comment by cxhernandez** [comment]
@jeiros: Any chance you could provide us with a PDB that reproduces this issue?

**Comment by jeiros** [comment]
Hi,
I'm uploading two PDBs of the system: one has the phosphorylated serines named S1P, and the other has them as SER. 
I usually work with prmtop files though, maybe you want one to reproduce the error?
Thanks for taking a look at this.
[pdbs.zip](https://github.com/mdtraj/mdtraj/files/458824/pdbs.zip)
