### ISSUE TITLE
Writing a single frame to a PDB with mdconvert fails

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#1215]
I have an MDTraj HDF5 trajectory that I can convert to multiple other formats or slice with `mdconvert` without issues, but writing a single frame to PDB format fails:
```
[chodera@mskcc-ln1 ~/tmp-aurka]$ mdconvert -o output.pdb --index 0 /cbio/jclab/projects/fah/fah-data/munged3/all-atoms/11414/run0-clone0.h5
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda3/bin/mdconvert", line 6, in <module>
    sys.exit(mdtraj.scripts.mdconvert.entry_point())
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/mdtraj/scripts/mdconvert.py", line 500, in entry_point
    main(args)
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/mdtraj/scripts/mdconvert.py", line 288, in main
    atom_indices=atom_indices)
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/mdtraj/scripts/mdconvert.py", line 401, in read
    _data = infile.read(chunk, stride=stride, atom_indices=atom_indices)
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/mdtraj/formats/hdf5.py", line 607, in read
    out_units='nanometers', can_be_none=False),
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/mdtraj/formats/hdf5.py", line 598, in get_field
    data =  in_units_of(data, in_units, out_units)
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/mdtraj/utils/unit/__init__.py", line 171, in in_units_of
    return quantity * factor
MemoryError
```

**Comment by jchodera** [comment]
Whoops, I somehow missed the `MemoryError` part of that stack trace. This is probably on my end.
