### ISSUE TITLE
md.load fails with top=str and atom_indices

### ISSUE THREAD

**Issue by justinrporter** [mdtraj/mdtraj#1249]
**Probable duplicate of #1234... (which I didn't see it until just now)**

I discovered today that the following code will error out on an assertion:

```python
from mdtraj.testing import get_fn

top=md.load(get_fn('native.pdb')).top

md.load(get_fn('frame0.xtc'),
        top=get_fn('native.pdb'),
        atom_indices=top.select('name CA'))
```

whereas the following code will execute just fine:

```python
from mdtraj.testing import get_fn

top=md.load(get_fn('native.pdb')).top

md.load(get_fn('frame0.xtc'),
        top=top,
        atom_indices=top.select('name CA'))
```

Stack trace:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    atom_indices=top.select('name CA'))
  File "/Users/jrporter/projects/.venvs/stag3/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 372, in load
    kwargs["top"] = _parse_topology(kwargs["top"], **topkwargs)
  File "/Users/jrporter/projects/.venvs/stag3/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 169, in _parse_topology
    _traj = load_frame(top, 0, **kwargs)
  File "/Users/jrporter/projects/.venvs/stag3/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 311, in load_frame
    return loader(filename, frame=index, **kwargs)
  File "/Users/jrporter/projects/.venvs/stag3/lib/python3.5/site-packages/mdtraj/formats/pdb/pdbfile.py", line 159, in load_pdb
    assert coords.ndim == 3, 'internal shape error'
AssertionError: internal shape error
```

I imagine that this is some kind of problem with the shape of the topology that gets loaded when you provide a string as the topology path?

**Comment by mpharrigan** [comment]
Please try this with the new release of version 1.9 and re-open if the issue isn't fixed
