### ISSUE TITLE
Nosetests failed and Introduction To MDTraj errors

### ISSUE THREAD

**Issue by Alan-Rusty24** [mdtraj/mdtraj#1289]
OS : Ubuntu 16.04.3
Python 2.7.12
I've installed mdtraj using
pip install nose --user
pip install mdtraj --user

I tried going along with the documents and started with examples
1. Introduction to MDTraj and as I run the two commands i get errors. It seems like it couldn't find the file? I'd like to know how can i remedy this.
import mdtraj as md
t = md.load('trajectory.xtc', top='trajectory.pdb')
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-2-44213afc39fc> in <module>()
----> 1 t = md.load('trajectory.xtc')

/home/alankar/.local/lib/python2.7/site-packages/mdtraj/core/trajectory.pyc in load(filename_or_filenames, discard_overlapping_frames, **kwargs)
    422 
    423     if loader.__name__ not in ['load_dtr']:
--> 424         _assert_files_exist(filename_or_filenames)
    425     else:
    426         _assert_files_or_dirs_exist(filename_or_filenames)

/home/alankar/.local/lib/python2.7/site-packages/mdtraj/core/trajectory.pyc in _assert_files_exist(filenames)
     97     for fn in filenames:
     98         if not (os.path.exists(fn) and os.path.isfile(fn)):
---> 99             raise IOError('No such file: %s' % fn)
    100 
    101 

IOError: No such file: trajectory.xtc

2. When I ran 
nosetests mdtraj -v
It fails with 2 errors
======================================================================
ERROR: mdtraj.tests.test_arc.test_read_arctraj
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alankar/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/alankar/Work/Tutorials/Learn_MDTraj/mdtraj/build/testenv/lib/python2.7/site-packages/mdtraj/tests/test_arc.py", line 40, in test_read_arctraj
    traj = md.load(get_fn('nitrogen.arc'), top=get_fn('nitrogen.pdb'))
  File "/home/alankar/Work/Tutorials/Learn_MDTraj/mdtraj/build/testenv/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 430, in load
    value = loader(filename, **kwargs)
  File "/home/alankar/Work/Tutorials/Learn_MDTraj/mdtraj/build/testenv/lib/python2.7/site-packages/mdtraj/formats/arc.py", line 90, in load_arc
    atom_indices=atom_indices)
  File "/home/alankar/Work/Tutorials/Learn_MDTraj/mdtraj/build/testenv/lib/python2.7/site-packages/mdtraj/formats/arc.py", line 222, in read_as_traj
    xyz, abc, ang = self.read(n_frames=n_frames, stride=stride, atom_indices=atom_indices)
  File "/home/alankar/Work/Tutorials/Learn_MDTraj/mdtraj/build/testenv/lib/python2.7/site-packages/mdtraj/formats/arc.py", line 293, in read
    if None in lengths:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: Failure: ValueError (The truth value of an array with more than one element is ambiguous. Use a.any() or a.all())
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alankar/.local/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/alankar/Work/Tutorials/Learn_MDTraj/mdtraj/build/testenv/lib/python2.7/site-packages/mdtraj/tests/test_hdf5.py", line 111, in test_write_units2
    units.unit_definitions.angstroms)
  File "/home/alankar/Work/Tutorials/Learn_MDTraj/mdtraj/build/testenv/lib/python2.7/site-packages/mdtraj/utils/unit/quantity.py", line 170, in __init__
    if value == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

----------------------------------------------------------------------
Ran 1142 tests in 270.288s

FAILED (SKIP=23, errors=2)

**Comment by mpharrigan** [comment]
This is fixed with #1266
