### ISSUE TITLE
mdtraj downgrades numpy and gives error

### ISSUE THREAD

**Issue by jeiros** [mdtraj/mdtraj#1333]
Hi,

For some reason the numpy version that is being installed with mdtraj is crashing on my machine (osx high sierra 10.13). I'm using anaconda with python 3.6.

```
import mdtraj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/je714/miniconda3/lib/python3.6/site-packages/mdtraj/__init__.py", line 29, in <module>
    from .formats.registry import FormatRegistry
  File "/Users/je714/miniconda3/lib/python3.6/site-packages/mdtraj/formats/__init__.py", line 3, in <module>
    from .arc import ArcTrajectoryFile
  File "/Users/je714/miniconda3/lib/python3.6/site-packages/mdtraj/formats/arc.py", line 31, in <module>
    import numpy as np
  File "/Users/je714/miniconda3/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/Users/je714/miniconda3/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/je714/miniconda3/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Users/je714/miniconda3/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/je714/miniconda3/lib/python3.6/site-packages/numpy/core/__init__.py", line 38, in <module>
    from . import numeric
  File "/Users/je714/miniconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 12, in <module>
    from .multiarray import (
ImportError: cannot import name 'normalize_axis_index'
```
It doesn't matter if I preinstall numpy before installing mdtraj, since the installation downgrades it:
```
The following packages will be DOWNGRADED:

    numpy:        1.14.1-py36_blas_openblas_200 conda-forge [blas_openblas] --> 1.12.1-py36_blas_openblas_201 conda-forge [blas_openblas]
```

Do you  have an indication of what might be going on?

**Comment by jeiros** [comment]
Nevermind, I don't think it's a problem on your end. I was doing this on my horribly cluttered root environment, installing `mdtraj` on a new clean environment gives no issues.
