### ISSUE TITLE
Internal shape error

### ISSUE THREAD

**Issue by lvotapka** [mdtraj/mdtraj#1396]
Hello All,

I'm using mdtraj 1.9.2 to load a PDB file (PDB ID: 1yet, downloaded at https://files.rcsb.org/download/1YET.pdb)

If I run the following code I get an error:

<pre>
import mdtraj
ref_alpha_carbons_and_lig = [1, 8]
ref_struct = mdtraj.load_frame(filename='1yet.pdb', index=0, atom_indices=ref_alpha_carbons_and_lig)
</pre>

The error is:
<pre>
Traceback (most recent call last):
  File "test_mdtraj.py", line 4, in <module>
    ref_struct = mdtraj.load_frame(filename='1yet.pdb', index=0, atom_indices=ref_alpha_carbons_and_lig)
  File "/home/lvotapka/miniconda2/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 311, in load_frame
    return loader(filename, frame=index, **kwargs)
  File "/home/lvotapka/miniconda2/lib/python2.7/site-packages/mdtraj/formats/pdb/pdbfile.py", line 159, in load_pdb
    assert coords.ndim == 3, 'internal shape error'
AssertionError: internal shape error
</pre>

This error persisted even after using pip to install the latest version of mdtraj (1.9.2)

**Comment by lvotapka** [comment]
Thanks Martin, that's a good suggestion.
