### ISSUE TITLE
The bug when use .xyz and .pdb file convert the .lammpstrj 

### ISSUE THREAD

**Issue by ZengZezhu** [mdtraj/mdtraj#1474]
**I just encountered a problem when convert the .xyz file to .lammpstrj file. The Bug like below :**

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    t.save('hahaha.lammpstrj')
  File "/home/zengzz/anaconda3/lib/python3.6/site-packages/mdtraj/core/trajectory.py", line 1312, in save
    return saver(filename, **kwargs)
  File "/home/zengzz/anaconda3/lib/python3.6/site-packages/mdtraj/core/trajectory.py", line 1344, in save_lammpstrj
    cell_angles=self.unitcell_angles)
  File "/home/zengzz/anaconda3/lib/python3.6/site-packages/mdtraj/formats/lammpstrj.py", line 505, in write
    add_newaxis_on_deficient_ndim=True)
  File "/home/zengzz/anaconda3/lib/python3.6/site-packages/mdtraj/utils/validation.py", line 112, in ensure_type
    " You supplied type %s" % (name, type(val))))
TypeError: cell_lengths must be numpy array.  You supplied type <class 'NoneType'>

while I converted .xyz to .h5 is ok, so Could you give me some advices? many thanks

**Comment by rmcgibbo** [comment]
Hi, it looks like your lammp trajectory must be missing unit cell information, and we expect that data to be available.
