### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by MaryamSSadeghi** [mdtraj/mdtraj#1478]
Hi, I cannot find the issue related to this warning:

python pycgtool.py -g ref.gro -x md2.xtc -m PCL10.map -b PCL10.bnd
Using GRO: ref.gro
Using XTC: md2.xtc

WARNING: Using MDTraj which renames solvent molecules
Traceback (most recent call last):
File "/home/maryam/Desktop/CG-PCL10/pycgtool/framereader.py", line 34, in get_frame_reader
return readers[name](top, traj, frame_start)
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "pycgtool.py", line 65, in
main(args, config)
File "/home/maryam/Desktop/CG-PCL10/pycgtool/pycgtool.py", line 21, in main
frame = Frame(gro=args.gro, xtc=args.xtc, itp=args.itp, frame_start=args.begin)
File "/home/maryam/Desktop/CG-PCL10/pycgtool/frame.py", line 135, in init
self._trajreader = get_frame_reader(gro, traj=xtc, frame_start=frame_start)
File "/home/maryam/Desktop/CG-PCL10/pycgtool/framereader.py", line 41, in get_frame_reader
return reader(top, traj, frame_start)
File "/home/maryam/Desktop/CG-PCL10/pycgtool/framereader.py", line 202, in init
self._traj = mdtraj.load(trajname, top=topname)
File "/home/maryam/anaconda3/lib/python3.6/site-packages/mdtraj/core/trajectory.py", line 430, in load
value = loader(filename, **kwargs)
File "mdtraj/formats/xtc/xtc.pyx", line 165, in xtc.load_xtc (mdtraj/formats/xtc/xtc.c:2766)
File "mdtraj/formats/xtc/xtc.pyx", line 172, in xtc.load_xtc (mdtraj/formats/xtc/xtc.c:2720)
File "mdtraj/formats/xtc/xtc.pyx", line 336, in xtc.XTCTrajectoryFile.read_as_traj (mdtraj/formats/xtc/xtc.c:4579)
File "mdtraj/formats/xtc/xtc.pyx", line 407, in xtc.XTCTrajectoryFile.read (mdtraj/formats/xtc/xtc.c:5612)
File "mdtraj/formats/xtc/xtc.pyx", line 446, in xtc.XTCTrajectoryFile._read (mdtraj/formats/xtc/xtc.c:6959)
MemoryError

**Comment by rmcgibbo** [comment]
You don't have enough memory to read the trajectory in. MDTraj has functions to load the trajectory in chunks. See e.g. http://mdtraj.org/1.9.3/api/generated/mdtraj.iterload.html?highlight=iterload
