### ISSUE TITLE
mdconvert unicode decode error

### ISSUE THREAD

**Issue by ucbecla** [mdtraj/mdtraj#1547]
Hi,

I have just installed MDTRAJ within the Ubuntu terminal from the microsoft store on my windows 10 computer. 

I first ran sudo apt-get update and sudo apt-get upgrade.

Then I installed Anaconda 3 by following this website's instructions:
https://www.digitalocean.com/community/tutorials/how-to-install-the-anaconda-python-distribution-on-ubuntu-20-04

Then I installed MDTRAJ using "conda install -c conda-forge mdtraj"

Everything appears to have worked. When I run "mdconvert -h" it displays the information on how to use mdconvert.

When I actually try and run mdconvert to convert my MD files, I get this error message:
Traceback (most recent call last):
  File "/home/christophe/anaconda3/bin/mdconvert", line 11, in <module>
    sys.exit(entry_point())
  File "/home/christophe/anaconda3/lib/python3.7/site-packages/mdtraj/scripts/mdconvert.py", line 500, in entry_point
    main(args)
  File "/home/christophe/anaconda3/lib/python3.7/site-packages/mdtraj/scripts/mdconvert.py", line 246, in main
    atom_indices = np.loadtxt(args.atom_indices, int)
  File "/home/christophe/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1112, in loadtxt
    first_line = next(fh)
  File "/home/christophe/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Attached is a screenshot of this. I used this program about 2 months ago with no issue. Now I run it all exactly the same and this happens.

Does anyone know what might be the cause, and how to solve it ?

Many thanks,

Christophe.
![mdconvert](https://user-images.githubusercontent.com/65288282/81808316-705ab280-9517-11ea-8ba7-2339175cde13.JPG)

**Comment by ucbecla** [comment]
Ok nevermind it was just a formatting error in my "atoms.txt" file .... Issue solved.
