### ISSUE TITLE
segfault on i386 in geometry_wrap_mols

### ISSUE THREAD

**Issue by drew-parsons** [mdtraj/mdtraj#1591]
`test_image_molecules`  in test_trajectory.py segfaults on i386 (32-bit intel). Is this expected?

The undetailed test log is at https://ci.debian.net/packages/m/mdtraj/unstable/i386/
https://ci.debian.net/data/autopkgtest/unstable/i386/m/mdtraj/7711495/log.gz
This is a build from git master.

A gdb backtrace (`gdb python3`) reports:
```
(gdb) run -m pytest -k test_image_molecules --pdb test_trajectory.py
Starting program: /usr/bin/python3-dbg -m pytest -k test_image_molecules --pdb test_trajectory.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py:9: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[Detaching after fork from child process 32465]
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.8.6, pytest-4.6.11, py-1.9.0, pluggy-0.13.0 -- /usr/bin/python3-dbg
cachedir: .pytest_cache
rootdir: /home/dparsons/mdtraj/mdtraj-1.9.4+git20201015.068f29a, inifile: pytest.ini
collected 570 items / 569 deselected / 1 selected                                                                                                                                                                 

test_trajectory.py::test_image_molecules 
Program received signal SIGSEGV, Segmentation fault.
0xf7fb7fad in sem_wait@@GLIBC_2.1 () from /lib/i386-linux-gnu/libpthread.so.0
(gdb) bt
#0  0xf7fb7fad in sem_wait@@GLIBC_2.1 () from /lib/i386-linux-gnu/libpthread.so.0
#1  0x081693e6 in PyThread_acquire_lock_timed (lock=0x18e, microseconds=<optimized out>, intr_flag=0) at ../Python/thread_pthread.h:471
#2  0x0816956f in PyThread_acquire_lock (lock=0x18e, waitflag=1) at ../Python/thread_pthread.h:709
#3  0xf403de6d in __pyx_add_acquisition_count_locked (lock=0x18e, acquisition_count=0xf7be9030) at mdtraj/geometry/src/_geometry.cpp:25625
#4  __Pyx_INC_MEMVIEW (memslice=<optimized out>, memslice=<optimized out>, have_gil=1, lineno=5851) at mdtraj/geometry/src/_geometry.cpp:25650
#5  __pyx_f_6mdtraj_8geometry_9_geometry_wrap_mols (__pyx_v_frame_positions=..., __pyx_v_frame_unitcell_vectors=..., __pyx_v_center=..., __pyx_v_frame_positions=..., __pyx_v_frame_unitcell_vectors=..., 
    __pyx_v_center=..., __pyx_v_other_molecules=...) at mdtraj/geometry/src/_geometry.cpp:5851
#6  __pyx_f_6mdtraj_8geometry_9_geometry_image_frame (__pyx_v_frame_positions=<optimized out>, __pyx_v_frame_unitcell_vectors=<optimized out>, __pyx_v_anchor_molecules=<optimized out>, 
    __pyx_v_other_molecules=..., __pyx_v_sorted_bonds=<optimized out>) at mdtraj/geometry/src/_geometry.cpp:7090
#7  0xf4041a06 in __pyx_pf_6mdtraj_8geometry_9_geometry_24image_molecules (__pyx_self=<optimized out>, __pyx_v_sorted_bonds=<optimized out>, __pyx_v_other_molecules=<optimized out>, 
    __pyx_v_anchor_molecules=<optimized out>, __pyx_v_box=<optimized out>, __pyx_v_xyz=<optimized out>) at /usr/include/c++/10/bits/stl_algobase.h:560
#8  __pyx_pw_6mdtraj_8geometry_9_geometry_25image_molecules (__pyx_self=<optimized out>, __pyx_args=<optimized out>, __pyx_kwds=<optimized out>) at mdtraj/geometry/src/_geometry.cpp:7241
#9  0x080743e6 in cfunction_call_varargs (func=0xf40f7c60, args=0xf7b58bc8, kwargs=0x0) at ../Objects/call.c:742
#10 0x08076830 in PyCFunction_Call (func=0xf40f7c60, args=0xf7b58bc8, kwargs=0x0) at ../Objects/call.c:772
```

So the segfault seems to be coming from [`wrap_mols`](https://github.com/mdtraj/mdtraj/blob/068f29adeedb65b8d4e0ad6127a037e30cc6fd5e/mdtraj/geometry/src/image_molecules.pxi#L52) in `geometry/src/image_molecules.pxi`  by way of `add_acquisition_count_locked` in the generated c++ code calling `PyThread_acquire_lock` and `sem_wait` from libpthread.

Is mdtraj expected to work on 32-bit (i386) systems?

**Comment by rmcgibbo** [comment]
Thanks for the report. I'm pretty sure that 32-bit systems are totally untested  by the developers/users, so we're better off just saying "No 32-bit support".

**Comment by drew-parsons** [comment]
No problem.  All other tests pass, so in the Debian build I'll just skip this one test on i386 and let the package build proceed. Can monitor CI testing of the other tests at https://ci.debian.net/packages/m/mdtraj/unstable/i386/
and https://ci.debian.net/packages/m/mdtraj/testing/i386/
(the home for CI tests is https://ci.debian.net/packages/m/mdtraj/)

I'll treat the i386 build as "experimental" then.  If there are user reports of the same problem in actual usage outside of this test then we can kill the build.
