### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by debanjansen48** [mdtraj/mdtraj#1735]
PS C:\Users\HP\mdtraj-master> python setup.py install
C compiler:
Traceback (most recent call last):
  File "C:\Users\HP\mdtraj-master\setup.py", line 56, in <module>
    compiler.initialize()
  File "C:\Users\HP\mdtraj-master\.\basesetup.py", line 45, in initialize
    self._print_compiler_version(cc)
  File "C:\Users\HP\mdtraj-master\.\basesetup.py", line 108, in _print_compiler_version
    cc.initialize()
  File "C:\Program Files\Python310\lib\distutils\_msvccompiler.py", line 220, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\Program Files\Python310\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
    return _msvc14_get_vc_env(plat_spec)
  File "C:\Program Files\Python310\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
    raise distutils.errors.DistutilsPlatformError(
distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by debanjansen48** [comment]
i installed the packages mentioned in installation documentation. and the updated error given bellow

PS C:\Users\HP\Downloads> pip install mdtraj
Collecting mdtraj
  Using cached mdtraj-1.9.7.tar.gz (2.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      C compiler:
      Traceback (most recent call last):
        File "C:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-ra_fi65_\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-ra_fi65_\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-ra_fi65_\overlay\Lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-ra_fi65_\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 56, in <module>
          compiler.initialize()
        File "C:\Users\HP\AppData\Local\Temp\pip-install-zacsow7i\mdtraj_259a965dc92d42c2a47639381c11cdc4\.\basesetup.py", line 45, in initialize
          self._print_compiler_version(cc)
        File "C:\Users\HP\AppData\Local\Temp\pip-install-zacsow7i\mdtraj_259a965dc92d42c2a47639381c11cdc4\.\basesetup.py", line 95, in _print_compiler_version
          cc.initialize()
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-ra_fi65_\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-ra_fi65_\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-ra_fi65_\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by rmcgibbo** [comment]
For windows, you either need to download a pre-compiled version of mdtraj (maybe w/ conda), or you need to install the microsoft visual studio compiler, as the error message says.

**Comment by massgh** [comment]
> For windows, you either need to download a pre-compiled version of mdtraj (maybe w/ conda), or you need to install the microsoft visual studio compiler, as the error message says.

I tried on Ubuntu and Windows and even with cloning git repository but no success at all. The hardest and stubborn package in my coding history. This is a dependency of another package, and it messed up everything. Guys, please make it installable like `scipy` does.

**Comment by mattwthompson** [comment]
Hi @massgh, MDTraj is currently maintained by a team of (unpaid) volunteers. Please keep this in mind when asking for support. If you are having trouble, demands and criticism aren't likely to get you very far. What will help is ensuring you've [read the documentation](https://www.mdtraj.org/1.9.7/installation.html), and if something doesn't work, reporting bugs with [minimal reproducing examples.](https://stackoverflow.com/help/minimal-reproducible-example) I have no idea what to do with the information you've provided. Please make it easy for us to help you or probably nobody will choose to help.
