### ISSUE TITLE
mdconvert fails when dcd contains only one frame

### ISSUE THREAD

**Issue by ehb54** [mdtraj/mdtraj#1748]
Thank you for efforts on mdtraj

I wanted to alert you that 1.9.4 (installed via pip) fails converting a single frame dcd.
```
dcdplugin) file 'test.dcd' appears to contain no timesteps.
Traceback (most recent call last):
  File "/usr/local/bin/mdconvert", line 8, in <module>
    sys.exit(entry_point())
  File "/usr/local/lib/python3.8/dist-packages/mdtraj/scripts/mdconvert.py", line 500, in entry_point
    main(args)
  File "/usr/local/lib/python3.8/dist-packages/mdtraj/scripts/mdconvert.py", line 284, in main
    with InFileFormat(fn, 'r') as infile:
  File "mdtraj/formats/dcd/dcd.pyx", line 221, in mdtraj.formats.dcd.DCDTrajectoryFile.__cinit__
OSError: Could not open file: test.dcd
```

I was using [catdcd](https://www.ks.uiuc.edu/Development/MDTools/catdcd/) to extract a single frame and then `mdconvert` to make a `pdb` for visualization.

Issue is not a show-stopper, just have to create a 2 frame dcd instead.

**Comment by sukritsingh** [comment]
Does this issue still occur in 1.9.8?
