### ISSUE TITLE
Trajectory hashing fails if unitcell data is missing

### ISSUE THREAD

**Issue by CharlieLaughton** [mdtraj/mdtraj#1780]
The \_\_hash\_\_() method of a trajectory assumes that unitcell data (lengths and angles) are present as numpy arrays. If a trajectory is loaded that does not contain this data, they will be `None` and hashing will fail. One effect of this is seen in testing for the equality of two trajectories:

    import mdtraj as mdt
    t1 = mdt.load('1bpi.pdb')
    t2 = mdt.load('1bpi.pdb')
    t1 == t2
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/users/charlie/.local/lib/python3.9/site-packages/mdtraj/core/trajectory.py", line 974, in __eq__
        return self.__hash__() == other.__hash__()
      File "/users/charlie/.local/lib/python3.9/site-packages/mdtraj/core/trajectory.py", line 969, in __hash__
        hash_value ^= _hash_numpy_array(self._unitcell_lengths)
      File "/users/charlie/.local/lib/python3.9/site-packages/mdtraj/core/trajectory.py", line 120, in _hash_numpy_array
        hash_value = hash(x.shape)
    AttributeError: 'NoneType' object has no attribute 'shape'
     

I can provide a PR to fix this, if desired.

**Comment by mattwthompson** [comment]
Weird - if the fix is as simple as I imagine it is, we'd welcome a PR!

**Comment by CharlieLaughton** [comment]
OK, PR submitted
