### ISSUE TITLE
Cython 3 breaks cythonization of _geometry.pyx

### ISSUE THREAD

**Issue by jeremyleung521** [mdtraj/mdtraj#1800]
[Cython 3](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html) appears to break cythonization of `mdtraj/geometry/src/_geometry.pyx`.  Reproducible on MacOS and Linux.

To reproduce, install mdtraj without the wheels:
`python -m pip install mdtraj --no-binary :all:` 

Pinning cython to <3 in `pyproject.toml` will prevent the error from happening, but suggests some changes in `_geometry.pyx` is needed for cython 3 support.

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [160 lines of output]
      Apple clang version 14.0.3 (clang-1403.0.22.14.1)
      Target: arm64-apple-darwin22.5.0
      Thread model: posix
      InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
      /Users/User/Documents/Important/Pitt/git/mdtraj/basesetup.py:451: UserWarning: Unrecognized setuptools command ('dist_info --output-dir /private/var/folders/06/29rlbptd5jq_rfl__96vd2qh0000gn/T/pip-modern-metadata-a0z_scx1 --keep-egg-info'), proceeding with generating Cython sources and expanding templates
        warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
      warning: mdtraj/formats/dcd/dcdlib.pxd:12:12: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      warning: mdtraj/formats/dcd/dcdlib.pxd:12:16: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      warning: mdtraj/formats/dcd/dcdlib.pxd:12:20: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  offset[k] += frame_unitcell_vectors[0, k]*roundf((delta[0]-offset[0])/frame_unitcell_vectors[0,0])
                  frame_positions[atom2, k] = frame_positions[atom2, k] - offset[k]
      
      cdef void anchor_dists(float[:,::1] frame_positions,
                        float[:,::1] frame_unitcell_vectors,
                        vector[int[:]] anchor_molecules,
                              ^
      ------------------------------------------------------------
      
      mdtraj/geometry/src/image_molecules.pxi:33:24: Reference-counted type 'int[:]' cannot be used as a template argument
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  anchor_nearest_atoms[mol2, mol1, 1] = ca2
      
      cdef void wrap_mols(float[:,::1] frame_positions,
                          float[:,::1] frame_unitcell_vectors,
                          float[:] center,
                          vector[int[:]] other_molecules) nogil:
                                ^
      ------------------------------------------------------------
      
      mdtraj/geometry/src/image_molecules.pxi:55:26: Reference-counted type 'int[:]' cannot be used as a template argument
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      
      cdef void image_frame(frame_positions,
                       frame_unitcell_vectors,
                       anchor_molecules,
                       vector[int[:]] other_molecules,
                             ^
      ------------------------------------------------------------
      
      mdtraj/geometry/src/image_molecules.pxi:96:23: Reference-counted type 'int[:]' cannot be used as a template argument
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          anchor_atom_indices = np.concatenate(anchor_molecules)
          center = np.mean(frame_positions[anchor_atom_indices], axis=0)
          wrap_mols(frame_positions, frame_unitcell_vectors, center, other_molecules)
      
      def image_molecules(xyz, box, anchor_molecules, other_molecules, sorted_bonds):
          cdef vector[int[:]] omol = other_molecules
                     ^
      ------------------------------------------------------------
      
      mdtraj/geometry/src/image_molecules.pxi:144:15: Reference-counted type 'int[:]' cannot be used as a template argument
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef int[:] mol
          cdef float mol_center[3]
          cdef float mol_offset[3]
      
          cdef int n
          for i in range(other_molecules.size()):
                                             ^
      ------------------------------------------------------------
      
      mdtraj/geometry/src/image_molecules.pxi:72:39: Coercion from Python not allowed without the GIL
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef int[:] mol
          cdef float mol_center[3]
          cdef float mol_offset[3]
      
          cdef int n
          for i in range(other_molecules.size()):
                                             ^
      ------------------------------------------------------------
      
      mdtraj/geometry/src/image_molecules.pxi:72:39: Calling gil-requiring function not allowed without gil
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef int[:] mol
          cdef float mol_center[3]
          cdef float mol_offset[3]
      
          cdef int n
          for i in range(other_molecules.size()):
                                        ^
      ------------------------------------------------------------
      
      mdtraj/geometry/src/image_molecules.pxi:72:34: Accessing Python attribute not allowed without gil
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef int[:] mol
          cdef float mol_center[3]
          cdef float mol_offset[3]
      
          cdef int n
          for i in range(other_molecules.size()):
                                             ^
      ------------------------------------------------------------
      
      mdtraj/geometry/src/image_molecules.pxi:72:39: Constructing Python tuple not allowed without gil
      C compiler:
      Attempting to autodetect OpenMP support... Did not detect OpenMP support
      Attempting to autodetect SSE2   support... Did not detect SSE2 support
      Attempting to autodetect SSE3   support... Did not detect SSE3 support
      Attempting to autodetect SSE4.1 support... Did not detect SSE4.1 support
      Attempting to autodetect NEON   support... Compiler supports NEON
      
      [ 1/12] Cythonizing mdtraj/formats/binpos/binpos.pyx
      [ 2/12] Cythonizing mdtraj/formats/dcd/dcd.pyx
      [ 3/12] Cythonizing mdtraj/formats/dtr/dtr.pyx
      [ 4/12] Cythonizing mdtraj/formats/tng/tng.pyx
      [ 5/12] Cythonizing mdtraj/formats/xtc/trr.pyx
      [ 6/12] Cythonizing mdtraj/formats/xtc/xtc.pyx
      [ 7/12] Cythonizing mdtraj/geometry/drid.pyx
      [ 8/12] Cythonizing mdtraj/geometry/neighborlist.pyx
      [ 9/12] Cythonizing mdtraj/geometry/neighbors.pyx
      [10/12] Cythonizing mdtraj/geometry/src/_geometry.pyx
      Traceback (most recent call last):
        File "/Users/User/miniconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/User/miniconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/User/miniconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/06/29rlbptd5jq_rfl__96vd2qh0000gn/T/pip-build-env-4ldm9nf3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/06/29rlbptd5jq_rfl__96vd2qh0000gn/T/pip-build-env-4ldm9nf3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/06/29rlbptd5jq_rfl__96vd2qh0000gn/T/pip-build-env-4ldm9nf3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 304, in <module>
        File "/private/var/folders/06/29rlbptd5jq_rfl__96vd2qh0000gn/T/pip-build-env-4ldm9nf3/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/06/29rlbptd5jq_rfl__96vd2qh0000gn/T/pip-build-env-4ldm9nf3/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: mdtraj/geometry/src/_geometry.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by mattwthompson** [comment]
I wasn't sure if Cython 3 was ever going to come out, but this isn't much of a surprise. I bet there's more code that needs to be updated.

We should definitely pin to version 2 for the time being.

**Comment by mattwthompson** [comment]
https://github.com/conda-forge/mdtraj-feedstock/pull/49

**Comment by mattwthompson** [comment]
What needs to be done to fix things on the PyPI side of things? I assume updating the TOML file won't impact the sdist that's already released and uploaded?

**Comment by jeremyleung521** [comment]
Correct. After the TOML file fix commit, you'll need to push an additional bug fix release to PyPI to fix new installs. It would probably require a new version number (`1.9.9` or [with](https://snarky.ca/what-to-do-when-you-botch-a-release-on-pypi/) `1.9.8.post1`, though I've never personally used the `post1` thing before).

**Comment by vid277** [comment]
Is this error fixed and can it be installed through Pip? Is a downgrade in Cython versions necessary? I am running mdtraj from Google Colab and receiving a similar error.

**Comment by mattwthompson** [comment]
> Is a downgrade in Cython versions necessary?

Yes, that's the solution

**Comment by mattwthompson** [comment]
This should be resolved with release 1.9.9 - thanks again to @jeremyleung521 for bringing this to our attention and guiding us through to a fix

If there are any deployment issues with that release, please share them here: https://github.com/mdtraj/mdtraj/discussions/1805

**Comment by mgorny** [comment]
Could you please reopen the bug, to track support for Cython 3? At this point Cython 0.29* is no longer maintained, and is already facing first bugs related to GCC 14 (not saying mdtraj is affected, I haven't tried, just saying from a wider perspective of a distribution that aims to remove Cython<3 altogether).

**Comment by mattwthompson** [comment]
A PR to migrate to Cython 3 would be welcome; for now our builds of existing are working, if that changes we'd have to revisit things

**Comment by eli-schwartz** [comment]
> Could you please reopen the bug, to track support for Cython 3? At this point Cython 0.29* is no longer maintained, and is already facing first bugs related to GCC 14 (not saying mdtraj is affected, I haven't tried, just saying from a wider perspective of a distribution that aims to remove Cython<3 altogether).

Funnily enough, mdtraj *is* affected:

```
x86_64-pc-linux-gnu-gcc -Wsign-compare -DNDEBUG -march=native -fstack-protector-all -O2 -pipe -fdiagnostics-color=always -frecord-gcc-switches -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-clash-protection -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wformat -Werror=format-security -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=incompatible-pointer-types -fPIC -DUSE_ZLIB=1 -Imdtraj/formats/tng/include -I/usr/include -I/usr/lib/python3.11/site-packages/numpy/core/include -I/usr/include/python3.11 -c mdtraj/formats/tng/src/lib/tng_io.c -o /var/tmp/portage/sci-chemistry/mdtraj-1.9.7/work/mdtraj-1.9.7-python3_11/temp.linux-x86_64-3.11/mdtraj/formats/tng/src/lib/tng_io.o
mdtraj/formats/tng/src/lib/tng_io.c: In function ‘tng_block_header_read’:
mdtraj/formats/tng/src/lib/tng_io.c:1064:57: error: assignment to ‘tng_function_status (*)(struct tng_trajectory * const,  int32_t *)’ {aka ‘tng_function_status (*)(struct tng_trajectory * const,  int *)’} from incompatible pointer type ‘tng_function_status (*)(struct tng_trajectory * const,  uint32_t *)’ {aka ‘tng_function_status (*)(struct tng_trajectory * const,  unsigned int *)’} [-Werror=incompatible-pointer-types]
 1064 |                 tng_data->input_endianness_swap_func_32 =
      |                                                         ^
mdtraj/formats/tng/src/lib/tng_io.c:1073:57: error: assignment to ‘tng_function_status (*)(struct tng_trajectory * const,  int64_t *)’ {aka ‘tng_function_status (*)(struct tng_trajectory * const,  long int *)’} from incompatible pointer type ‘tng_function_status (*)(struct tng_trajectory * const,  uint64_t *)’ {aka ‘tng_function_status (*)(struct tng_trajectory * const,  long unsigned int *)’} [-Werror=incompatible-pointer-types]
 1073 |                 tng_data->input_endianness_swap_func_64 =
      |                                                         ^
mdtraj/formats/tng/src/lib/tng_io.c:1089:57: error: assignment to ‘tng_function_status (*)(struct tng_trajectory * const,  int32_t *)’ {aka ‘tng_function_status (*)(struct tng_trajectory * const,  int *)’} from incompatible pointer type ‘tng_function_status (*)(struct tng_trajectory * const,  uint32_t *)’ {aka ‘tng_function_status (*)(struct tng_trajectory * const,  unsigned int *)’} [-Werror=incompatible-pointer-types]
 1089 |                 tng_data->input_endianness_swap_func_32 =
      |                                                         ^
mdtraj/formats/tng/src/lib/tng_io.c:1098:57: error: assignment to ‘tng_function_status (*)(struct tng_trajectory * const,  int64_t *)’ {aka ‘tng_function_status (*)(struct tng_trajectory * const,  long int *)’} from incompatible pointer type ‘tng_function_status (*)(struct tng_trajectory * const,  uint64_t *)’ {aka ‘tng_function_status (*)(struct tng_trajectory * const,  long unsigned int *)’} [-Werror=incompatible-pointer-types]
 1098 |                 tng_data->input_endianness_swap_func_64 =
      |                                                         ^
```

It is just that this particular code isn't a cythonized file.
