### ISSUE TITLE
Memory issues when appending with XTCReporter

### ISSUE THREAD

**Issue by ianbongalonta** [mdtraj/mdtraj#1840]
Hi everyone, 

I am trying to use the MDTraj XTCReporter with OpenMM to write to a .xtc file. I have successfully used it to run a 500 us trajectory with positions saved every 20 fs (yes, a lot, but very necessary for my method) but am unable to append to the existing trajectory due to memory issues:

My code:

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout
from mdtraj.reporters import XTCReporter
import os

# System preparation

gro = GromacsGroFile('VPG_solv_ions.gro')
top = GromacsTopFile('topol.top', periodicBoxVectors=gro.getPeriodicBoxVectors(),
        includeDir=os.getcwd())
system = top.createSystem(nonbondedMethod=PME, nonbondedCutoff=1.2*nanometer,
        constraints=HBonds)
T = 283.15
integrator = LangevinMiddleIntegrator(T*kelvin, 1/picosecond, 0.002*picoseconds)
platform = Platform.getPlatformByName("CUDA")

simulation = Simulation(top.topology, system, integrator, platform=platform)
# save coordinates every 10 x 2 fs = 20 fs for Amide I simulation
#simulation.reporters.append(XTCReporter('spec_prod.xtc', 10))
simulation.reporters.append(XTCReporter('spec_prod.xtc', 10, append=True))
simulation.reporters.append(StateDataReporter('spec_prod.log', 500, step=True,
        potentialEnergy=True,
        kineticEnergy=True,
        totalEnergy=True,
        temperature=True,
        volume=True,
        density=True,
        #remainingTime=True,
        speed=True,
        elapsedTime=True,
        separator="\t"))
#simulation.reporters.append(CheckpointReporter('spec_prod.chk', 25000))
simulation.reporters.append(CheckpointReporter('spec_prod_cont01.chk', 25000))

#restart_file = 'equil.chk'
restart_file = 'spec_prod.chk'
with open(restart_file, "rb") as f:
    simulation.context.loadCheckpoint(f.read())

simulation.step(250000000) # 500 ns (system already equilibrated)
```

Error:

```
usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'activate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'doctor', 'content-trust', 'env')
Traceback (most recent call last):
  File "prod_cont01.py", line 22, in <module>
    simulation.reporters.append(XTCReporter('spec_prod.xtc', 10, append=True))
  File "/beagle3/dinner/ianjefab/miniconda3/envs/openmm/lib/python3.8/site-packages/mdtraj/reporters/xtcreporter.py", line 79, in __init__
    contents = f.read()
  File "mdtraj/formats/xtc/xtc.pyx", line 408, in mdtraj.formats.xtc.XTCTrajectoryFile.read
  File "mdtraj/formats/xtc/xtc.pyx", line 446, in mdtraj.formats.xtc.XTCTrajectoryFile._read
numpy.core._exceptions.MemoryError: Unable to allocate 4.59 TiB for an array with shape (26575248, 15820, 3) and data type float32
Exception ignored in: <function _BaseReporter.__del__ at 0x7ff2ac777670>
Traceback (most recent call last):
  File "/beagle3/dinner/ianjefab/miniconda3/envs/openmm/lib/python3.8/site-packages/mdtraj/reporters/basereporter.py", line 261, in __del__
    self.close()
  File "/beagle3/dinner/ianjefab/miniconda3/envs/openmm/lib/python3.8/site-packages/mdtraj/reporters/basereporter.py", line 265, in close
    self._traj_file.close()
AttributeError: 'XTCReporter' object has no attribute '_traj_file'
```

I am able to use OpenMM's `DCDReporter` to do this just fine in .dcd format with no memory issues, but I need the trajectories in .xtc format for compatibility with my program. The error only pops up when `append=True`. I think that the issue lies in the program attempting to load the entire existing trajectory into memory. 

Is there a way I could get around this? Or, would it be quicker/easier to just run two 500 us trajectories and append them later?

Thanks in advance!

- Ian B.

**Comment by sukritsingh** [comment]
Thanks for bringing this up! IIRC (will need to double check), `XTCReporter` may not write everything out to disk right away but rather holds the trajectory in memory for easy appending/writing, which can lead to memory bloat really quick. I also am not entirely sure the `append=True` is fully supported (I'll need to check, but maybe it overwrites the object entirely every single time it appends?)

I also note that the trajectory filesize you're creating is _massive_ for memory (4 TB!): 
```
Unable to allocate 4.59 TiB for an array with shape (26575248, 15820, 3) and data type float32
```

A few ways forward that I can see:
1. It's great that you can write your trajectories in DCD format! Assuming you can can load the trajectory into memory, you could easily just do a three line conversion: 
```
traj = md.load('traj.dcd', 'topology.pdb')
traj.save_xtc('traj.xtc')
```

2. You could easily write the trajectories out in smaller chunks and then concatenate them together using `md.join` or the like. 
3. You don't need MDTraj at all! OpenMM 8.1 comes with an `XTCReporter` natively, which will allow you to write to XTC files using more modernized code. Version 8.1 of OpenMM is currently in [public beta](https://github.com/openmm/openmm/releases/tag/8.1.0beta) for the moment but should still meet your needs!

**Comment by peastman** [comment]
OpenMM 8.1 (just released today!) adds a built in XTC reporter.  Give it a try and see if it works for you?

**Comment by ianbongalonta** [comment]
Hi everyone,

Thanks for the responses--what a good coincidence about the release!

I tried it, though the MDTraj XTC writer is much, much faster (~500 ns per day) than the new one built in OpenMM (~33 ns  per day). Changing the output frequency from every 20 fs (which is unfortunately necessary for my spectral simulation) by 1000 times to every 20 ps brings the speed back up to ~600 ns per day.

Is this an issue with my setup, or the new XTC writer itself?

**Comment by sukritsingh** [comment]
> When XTCReporter retrieves the positions from the State, it calls state.getPositions() rather than state.getPositions(asNumpy=True).

Do you mean `state.getPositions()` in [this line](https://github.com/openmm/openmm/blob/432b5838f6a045882adfe2c4b3941bd65d6f0f12/wrappers/python/openmm/app/xtcreporter.py#L74)? Also, would `state.getPeriodicBoxVectors()` also need `asNumpy=True`?

Happy to submit a PR or open an Issue in the OpenMM repo if you want!

**Comment by peastman** [comment]
Right.  It's only `getPositions()` that matters.  We should also make the same change in the DCD, PDB, and PDBx reporters.  Of course, we also should test first to make sure that's really the cause of the slow performance.

A PR would be great.

**Comment by sukritsingh** [comment]
> Of course, we also should test first to make sure that's really the cause of the slow performance.

Agreed - I have a couple systems around I can test with prior to opening a PR (will report back).

Will need to test: 
1. To make sure that it is indeed `getPositions()` causes the slow performance 
2. A range of save frequency values to show that this slowdown occurs/is solved across a range of saving frequencies (since this was only found by having a very high save frequency)

Will report back, but let me know if there are other points to test for!

**Comment by tonigi** [comment]
I was under the impression that the memory-occupation problem when appending comes from https://github.com/mdtraj/mdtraj/blob/b1279864058200f9c43373d4cb186177e2fc49ab/mdtraj/reporters/xtcreporter.py#L79C39-L79C39 .  This makes restarts impossible when the trajectory size increases.

**Comment by sukritsingh** [comment]
Okay so I've run a quick litmus test where I ran 1 ns simulations at 4fs timestep using a protein system I have (~60K atoms). 

I varied both whether or not `asNumpy=True` was included in `xtcreporter.py` *and* the save frequency. I also did a direct test using our MDTraj reporter. Results are reported in below: 

| Reporter used | Save frequency (steps) | `asNumpy=True` included? | Speed (ns/day) |
|----------------|------------------------|------------------------|----------------|
| OpenMM 8.1            | 10                     | No                     | 66.4           |
| OpenMM 8.1            | 500                    | No                     | 584            |
| OpenMM 8.1            | 10                     | Yes                    | 90.6           |
| OpenMM 8.1            | 500                    | Yes                    | 625            |
| MDTraj            | 10                    | N/A                    | 596            |
| MDTraj            | 500                    | N/A                    | 670            |


@peastman It looks like adding `asNumpy=True` does technically speed things up for the `xtcreporter` but it's still severely limited when you have a high save frequency. It also looks like using the MDTraj reporter sidesteps this slowdown issue, so I think we're seeing that this issue is not configuration/system specific. Any thoughts?

**Comment by peastman** [comment]
I found the problem.  I created a PR with the fixes at https://github.com/openmm/openmm/pull/4330.  Want to try it out and see how it is now?

**Comment by sukritsingh** [comment]
Compiling the PR build now! I have to step away for tonight but will report back once I test it!

**Comment by sukritsingh** [comment]
Okay! New table below with the results - I'm only including the new tests: 

| Reporter used | Save frequency (steps) | Speed (ns/day) |
|----------------|------------------------|------------------------|
| OpenMM 8.1  XTC (fixed)          | 10                     |567          |
| OpenMM 8.1 XTC (fixed)            | 500                    | 682            |


This is a massive speedup across the board, and definitely comparable now to the MDTraj reporter!

I'll crosspost these results into the PR for posterity

**Comment by sukritsingh** [comment]
> The rows are labelled the same?

Correct it's the same PR repo but the only thing I varied was the save frequency (middle column)

**Comment by mattwthompson** [comment]
Ah, of course. That makes more sense

**Comment by sukritsingh** [comment]
With the advent of the OpenMM reporter fix, c this issue can be closed now?
