### ISSUE TITLE
MDTraj can write some PDB files that it cannot read

### ISSUE THREAD

**Issue by mattwthompson** [mdtraj/mdtraj#1903]
I think that solution proposed in this PR is not consistent with `mdtraj` writing functionality of pdb files. This can lead to a situation, when a structure read and then saved by `mdtraj` cannot be read again. Let me provide an example:
Let's assume that I have a cif file with a huge amount of waters (
`.cif` file in the archive [mdtraj_numbering_issue.zip](https://github.com/user-attachments/files/15928227/mdtraj_numbering_issue.zip)
). Then I can load this file to `mdtraj` and save it to `pdb`:
```python
st = md.load("tmp_hoh.cif")
st.save("tmp_hoh_pdb_1.pdb")
```
The residue numbering in the created file for waters will go from 1 to 9999 and then from 0 to 4989. This is in accordance with [writing behaviour](https://github.com/mdtraj/mdtraj/blob/ccd0c874361e4e31127e3803d3670d08d57f7933/mdtraj/formats/pdb/pdbfile.py#L396)

Then if I read the created file again and write it again:
```python
st = md.load("tmp_hohpdb_1.pdb")
st.save("tmp_hoh_pdb_2.pdb")
```
The ordering in the created file is already different: it goes from 1 to 2709, and then it is reset to 0 (thinking that the formatting is `hex`). This is still maybe ok, but then `mdtraj` cannot read this file anymore:
```python
st = md.load("tmp_hohpdb_2.pdb")
```
leads to an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pbuslaev/conda_env/astex_fep_dev/lib/python3.11/site-packages/mdtraj/core/trajectory.py", line 396, in load
    kwargs["top"] = _parse_topology(
                    ^^^^^^^^^^^^^^^^
  File "/home/pbuslaev/conda_env/astex_fep_dev/lib/python3.11/site-packages/mdtraj/core/trajectory.py", line 170, in _parse_topology
    _traj = load_frame(top, 0, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pbuslaev/conda_env/astex_fep_dev/lib/python3.11/site-packages/mdtraj/core/trajectory.py", line 313, in load_frame
    return loader(filename, frame=index, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pbuslaev/conda_env/astex_fep_dev/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbfile.py", line 152, in load_pdb
    with PDBTrajectoryFile(filename, standard_names=standard_names, top=top) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pbuslaev/conda_env/astex_fep_dev/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbfile.py", line 289, in __init__
    self._read_models()
  File "/home/pbuslaev/conda_env/astex_fep_dev/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbfile.py", line 608, in _read_models
    pdb = PdbStructure(self._file, load_all_models=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pbuslaev/conda_env/astex_fep_dev/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbstructure.py", line 283, in __init__
    self._load(input_stream)
  File "/home/pbuslaev/conda_env/astex_fep_dev/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbstructure.py", line 299, in _load
    self._add_atom(Atom(pdb_line, self))
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/pbuslaev/conda_env/astex_fep_dev/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbstructure.py", line 875, in __init__
    self.residue_number = _read_residue_number(pdb_line[22:26], pdbstructure, None, self)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pbuslaev/conda_env/astex_fep_dev/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbstructure.py", line 150, in _read_residue_number
    pdbstructure._residue_num_nondec_mode = pdbstructure._residue_num_initial_nodec_vals[
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '   0'
```

So it is at least strange that `mdtraj` is producing structures that can not be read back into `mdtraj`

_Originally posted by @pbuslaev in https://github.com/mdtraj/mdtraj/issues/1849#issuecomment-2182757651_

**Comment by sukritsingh** [comment]
> The residue numbering in the created file for waters will go from 1 to 9999 and then from 0 to 4989. This is in accordance with [writing behaviour](https://github.com/mdtraj/mdtraj/blob/ccd0c874361e4e31127e3803d3670d08d57f7933/mdtraj/formats/pdb/pdbfile.py#L396)

This is what sticks out to me most. It seems like while we are capable of reading files where numbering goes >9999, we haven't updated the writing behavior to write that out, and still write out the "old" behavior. We likely need to update the writing behavior

My suspicion is that this crash is occurring also because of the above "reset to 0" issue – It's reading two residues each with `resSeq=0` but will need to verify

**Comment by pbuslaev** [comment]
I am not 100% sure, but I also think there is a typo in the code: https://github.com/mdtraj/mdtraj/pull/1849/files#r1648933550

> This is what sticks out to me most. It seems like while we are capable of reading files where numbering goes >9999, we haven't updated the writing behavior to write that out, and still write out the "old" behavior. We likely need to update the writing behavior

The old writing behaviour is nice and understandable. Similar writing behaviour is implemented [elsewhere](https://biopython.org/wiki/Reading_large_PDB_files.html). I am actually happy with it. I think that the problem is with assigning the residue numbering mode logics. I cannot say exactly what is going wrong, I will need a lot more debugging to do, but even with randomly set residue numbers the reading logics fails with the same error. Here is a pdb example:
```
REMARK   1 CREATED WITH MDTraj 1.10.0, 2024-06-19
CRYST1   85.217   83.342   84.649  90.00  90.00  90.00 P 1           1
MODEL        0
ATOM      1  O   HOH F9320      31.572   0.164  14.767  1.00  0.00           O
ATOM      2  H1  HOH F9320      30.684  -0.181  14.861  1.00  0.00           H
ATOM      3  H2  HOH F9320      31.834  -0.087  13.881  1.00  0.00           H
ATOM      4  O   HOH F9999      40.788  -1.887  21.393  1.00  0.00           O
ATOM      5  H1  HOH F9999      40.392  -1.667  22.237  1.00  0.00           H
ATOM      6  H2  HOH F9999      40.925  -2.834  21.433  1.00  0.00           H
ATOM      7  O   HOH F   0      37.157   2.175  21.325  1.00  0.00           O
ATOM      8  H1  HOH F   0      36.682   2.159  20.494  1.00  0.00           H
ATOM      9  H2  HOH F   0      38.065   1.989  21.086  1.00  0.00           H
ATOM     10  O   HOH F   1      36.679   3.732  14.083  1.00  0.00           O
ATOM     11  H1  HOH F   1      36.627   2.948  14.630  1.00  0.00           H
ATOM     12  H2  HOH F   1      37.597   3.779  13.816  1.00  0.00           H
TER      13      HOH F12
END
```

**Comment by jeremyleung521** [comment]
Just had a quick look (since I co-wrote that PR).

So the overall problem was that the "startover convention" (loop 9999 back to 0) is not one of the reading modes I've added, so the logic-shorted at the read of 2710 (HEX mode) and internally push the next residue number to 10000, which contributed to how the write for the second pdb is different. 

```
In [2]: b = mdtraj.load('tmp_hoh_pdb_1.pdb')

In [3]: b.topology.chain(3).residue(2708)
Out[3]: HOH2709

In [4]: b.topology.chain(3).residue(2709)
Out[4]: HOH10000
```

It should fix the read/write discrepancy. I'll add a PR to fix this.

**Comment by jeremyleung521** [comment]
#1904 should fix this. It ended up being a bug where `mdtraj` reading all resid 2710+ in "hex mode". Don't know what I wrote back then with those conditionals that don't even make sense. The PR is ready to be reviewed.

**Comment by apayne97** [comment]
Just wanted to chime in here that I had the same problem! I had been using version 1.9.9 locally and was confused why the same scripts weren't working on a recently-updated environment on the cluster. Now it makes sense. 

For posterity
```
  Traceback (most recent call last):
    File "/data1/choderaj/paynea/openproteinsim/science/20240628_clean_cclab_dataset_analysis/nextflow_scripts/bin/04_dry_for_fah.py", line 13, in 
      t = md.load_pdb(args.pdb_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/paynea/miniforge3/envs/asapdiscovery-production/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbfile.py", line 152, in load_pdb
      with PDBTrajectoryFile(filename, standard_names=standard_names, top=top) as f:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/paynea/miniforge3/envs/asapdiscovery-production/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbfile.py", line 289, in __init__
      self._read_models()
    File "/home/paynea/miniforge3/envs/asapdiscovery-production/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbfile.py", line 608, in _read_models
      pdb = PdbStructure(self._file, load_all_models=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/paynea/miniforge3/envs/asapdiscovery-production/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbstructure.py", line 280, in __init__
      self._load(input_stream)
    File "/home/paynea/miniforge3/envs/asapdiscovery-production/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbstructure.py", line 296, in _load
      self._add_atom(Atom(pdb_line, self))
                     ^^^^^^^^^^^^^^^^^^^^
    File "/home/paynea/miniforge3/envs/asapdiscovery-production/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbstructure.py", line 872, in __init__
      self.residue_number = _read_residue_number(pdb_line[22:26], pdbstructure, None, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/paynea/miniforge3/envs/asapdiscovery-production/lib/python3.11/site-packages/mdtraj/formats/pdb/pdbstructure.py", line 147, in _read_residue_number
      pdbstructure._residue_num_nondec_mode = pdbstructure._residue_num_initial_nodec_vals[
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  KeyError: '9753'
  ```
  Looking forward to using the fixed version!
