### ISSUE TITLE
six module removed but still referenced, breaking mdinspect

### ISSUE THREAD

**Issue by drew-parsons** [mdtraj/mdtraj#1907]
mdtraj 1.10.0 removed `utils/six.py`.  But it is still referenced by the geometry submodule at

https://github.com/mdtraj/mdtraj/blob/ccd0c874361e4e31127e3803d3670d08d57f7933/mdtraj/geometry/internal.py#L37

`geometry/internal.py` is almost not used at all, except that it is used by `scripts/mdinspect.py`

Hence the mdinspect script does not work with mdtraj 1.10.0

```
$ mdinspect 
Traceback (most recent call last):
  File "/usr/bin/mdinspect", line 33, in <module>
    sys.exit(load_entry_point('mdtraj==1.9.10.dev0', 'console_scripts', 'mdinspect')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/mdinspect", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/mdtraj/scripts/mdinspect.py", line 38, in <module>
    from mdtraj.geometry.internal import COVALENT_RADII
  File "/usr/lib/python3/dist-packages/mdtraj/geometry/internal.py", line 37, in <module>
    from mdtraj.utils.six.moves import filter, xrange  # itertools
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'mdtraj.utils.six'

```

**Comment by jeremyleung521** [comment]
Hopefully #1908 will fix it. @drew-parsons, I don't really use mdinspect, so if you could test your use case using my branch in #1908, that'll be great!

**Comment by drew-parsons** [comment]
The patch works fine.  mdinspect runs without the error now.
