### ISSUE TITLE
Error converting amber .nc to gromacs .xtc

### ISSUE THREAD

**Issue by xavgit** [mdtraj/mdtraj#1914]
Hi,
I'm trying to convert a amber trajectory to a gromacs .xtc  using mdconvert with the following command:

 mdconvert -o 10_prod_md_step_000-1000_ns_no_wat_na_cl_mg.xtc  10_prod_md_step_000-1000_ns_no_wat_na_cl_mg.nc 
Traceback (most recent call last):
  File "/home/xxxx/.local/bin/mdconvert", line 8, in <module>
    sys.exit(entry_point())
  File "/home/xxxx/.local/lib/python3.8/site-packages/mdtraj/scripts/mdconvert.py", line 597, in entry_point
    main(args)
  File "/home/xxxx/.local/lib/python3.8/site-packages/mdtraj/scripts/mdconvert.py", line 324, in main
    with InFileFormat(fn, "r") as infile:
  File "/home/xxxx/.local/lib/python3.8/site-packages/mdtraj/formats/netcdf.py", line 169, in __init__
    self._handle = netcdf(filename, mode=mode, **input_args)
TypeError: __init__() got an unexpected keyword argument 'format'

Where I'm wrong?

There is an alternative way to make this conversion in mdtraj without using mdconvert?

Thanks.

Saverio

**Comment by mattwthompson** [comment]
I broke `mdconvert` in release 1.10.0. You could use either an older version (1.9) or try the Python API of 1.10.0.

The issue is which package handles the actual NetCDF stuff: https://github.com/mdtraj/mdtraj/pull/1895

It'd help if you posting your environment (`conda list` or equivalent)

**Comment by xavgit** [comment]
Ok.
Thanks.
[pip3_list.txt](https://github.com/user-attachments/files/16336969/pip3_list.txt)
Do you have an example to do the work of mdconvert with the Python API of 1.10.0?
Thanks again.

Saverio

**Comment by xavgit** [comment]
Hi,
using mdtraj 1.9.9 there are not error in the call but if I use the -t option then: 
$ mdconvert -o 10_prod_md_step_000-1000_ns_no_wat_na_cl_mg_mdconvert.xtc -f -t complex_sbox_oct_14.pdb 10_prod_md_step_000-1000_ns_no_wat_na_cl_mg.nc 
/home/xxxx/.local/lib/python3.8/site-packages/mdtraj/scripts/mdconvert.py:296: UserWarning: sdsfsd!!!!
  warnings.warn('sdsfsd!!!!')
Warning: 'topology' data from input file(s) will be discarded. output format only supports fields: 'xyz', 'time', 'step', 'box'
converted 10000 frames, 10224 atoms
If I don't use the -t option the warning is not present.
Can I use the produced .xtc file?

Thanks.

Saverio
