### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-16: ordinal not in range(128)

### ISSUE THREAD

**Issue by AthenACHY** [mdtraj/mdtraj#1953]
HI there,

I am new to mdtraj and I was trying to do PCA on the gromacs xtc file I obtained but run into an error when loading the .xtc file. 
>>> import mdtraj as md
>>> t='md_50ns_r2_WT_center_pymol.xtc'
>>> pdb="md_50ns_WT_center_pymol.pdb"
>>> 
>>> md.load(t, top=pdb)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/achu/anaconda3/envs/mdtraj/lib/python3.9/site-packages/mdtraj/core/trajectory.py", line 430, in load
    t = loader(tmp_file, **kwargs)
  File "mdtraj/formats/xtc/xtc.pyx", line 168, in mdtraj.formats.xtc.load_xtc
  File "mdtraj/formats/xtc/xtc.pyx", line 239, in mdtraj.formats.xtc.XTCTrajectoryFile.__cinit__
UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-16: ordinal not in range(128)

I also tried another function to read in the file but results in the same error:

>>> with md.formats.XTCTrajectoryFile(t) as f:
	xyz, time, step, box = f.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdtraj/formats/xtc/xtc.pyx", line 239, in mdtraj.formats.xtc.XTCTrajectoryFile.__cinit__
UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-16: ordinal not in range(128)

Loading the pdb file on its own is fine. so I wonder how I can fix it. The gromacs version I am using the gromacs 2023. And I set up a new conda environment and installed mdtraj via pip. 

thanks in advance.

**Comment by janash** [comment]
Is this still an issue? Is it only occurring with on XTC, or is it a problem more generally (does it occur with multiple XTC files)?

Would you be able to provide the files you are trying to load so that the error can be reproduced? (although I suppose the XTC may be large)
