### ISSUE TITLE
_ZSt28__throw_bad_array_new_lengthv

### ISSUE THREAD

**Issue by weigcdsb** [mdtraj/mdtraj#1954]
Traceback (most recent call last):
  File "runner/inference.py", line 27, in <module>
    from tools.analysis import metrics
  File "/hpc/home/gw74/FoldFlow/tools/analysis/metrics.py", line 2, in <module>
    import mdtraj as md
  File "/hpc/home/gw74/.local/lib/python3.8/site-packages/mdtraj/__init__.py", line 33, in <module>
    from mdtraj.core.trajectory import (
  File "/hpc/home/gw74/.local/lib/python3.8/site-packages/mdtraj/core/trajectory.py", line 58, in <module>
    from mdtraj.geometry import _geometry, distance
  File "/hpc/home/gw74/.local/lib/python3.8/site-packages/mdtraj/geometry/__init__.py", line 24, in <module>
    from .angle import *
  File "/hpc/home/gw74/.local/lib/python3.8/site-packages/mdtraj/geometry/angle.py", line 26, in <module>
    from mdtraj.geometry import _geometry, distance
ImportError: /hpc/home/gw74/.local/lib/python3.8/site-packages/mdtraj/geometry/_geometry.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

Let me know if any further information is needed for debugging.

**Comment by mattwthompson** [comment]
We need a minimal reproducing example - it's probably an installation issue, so reproducing it likely includes how you installed it

**Comment by weigcdsb** [comment]
Thanks @mattwthompson.
Basically, I use pip install mdtraj. 

If I tried to import the module, such as...
from mdtraj.geometry import _geometry, distance
the same error shows up.

**Comment by mattwthompson** [comment]
We need more information than that, i.e. `pip install mdtraj` works fine for me:

```shell
$ pip install mdtraj && python -c "import mdtraj as md; print(md.__version__)"
Collecting mdtraj
  Downloading mdtraj-1.10.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (1.6 kB)
Collecting numpy<2.0.0a0,>=1.23 (from mdtraj)
  Downloading numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl.metadata (61 kB)
Collecting scipy (from mdtraj)
  Downloading scipy-1.14.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting pyparsing (from mdtraj)
  Downloading pyparsing-3.2.0-py3-none-any.whl.metadata (5.0 kB)
Collecting packaging (from mdtraj)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Downloading mdtraj-1.10.1-cp312-cp312-macosx_11_0_arm64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 6.6 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl (13.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.7/13.7 MB 19.3 MB/s eta 0:00:00
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Downloading pyparsing-3.2.0-py3-none-any.whl (106 kB)
Downloading scipy-1.14.1-cp312-cp312-macosx_14_0_arm64.whl (23.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 22.2 MB/s eta 0:00:00
Installing collected packages: pyparsing, packaging, numpy, scipy, mdtraj
Successfully installed mdtraj-1.10.1 numpy-1.26.4 packaging-24.2 pyparsing-3.2.0 scipy-1.14.1
1.10.1
```

There's surely something else going on and we need more information than the basics (as tedious as it may be):
* What operating system?
* What CPU architecture?
* What virtual environment solution?
* What version of MDTraj is installed?
* What Python version is installed? I notice Python 3.8 in the traceback, which is very old and no longer supported by new versions of MDTraj and the ecosystem broadly. I recommend 3.10 at a minimum but really 3.12 where possible

**Comment by weigcdsb** [comment]
Thanks. Basically, I use the computing cluster from the university. Hope the following info can be helpful.

(base) gw74@dcc-mastatlab-gpu-01  ~/FoldFlow $ uname -a
Linux dcc-mastatlab-gpu-01 5.14.0-427.18.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 28 06:27:02 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
(base) gw74@dcc-mastatlab-gpu-01  ~/FoldFlow $ uname -m
x86_64
(base) gw74@dcc-mastatlab-gpu-01  ~/FoldFlow $ which python
/opt/apps/rhel8/Anaconda3-2021.05/bin/python
(base) gw74@dcc-mastatlab-gpu-01  ~/FoldFlow $ pip show mdtraj
Name: mdtraj
Version: 1.10.0
Summary: MDTraj: A modern, open library for the analysis of molecular dynamics trajectories
Home-page: http://mdtraj.org
Author: Robert McGibbon
Author-email: rmcgibbo@gmail.com
License: LGPLv2.1+
Location: /hpc/home/gw74/.local/lib/python3.8/site-packages
Requires: astunparse, packaging, scipy, numpy, pyparsing
Required-by:

**Comment by mattwthompson** [comment]
Please use Python 3.10, 3.11, or 3.12 as I recommended earlier
