### ISSUE TITLE
MDInspect blows up for large trajectories

### ISSUE THREAD

**Issue by kyleabeauchamp** [mdtraj/mdtraj#497]
```
=== f6792cf2-a959-4a0e-96aa-6.h5: Nonbonded Check (without PBCs) ===
Traceback (most recent call last):
  File "/home/kyleb/opt/bin/mdinspect", line 9, in <module>
    load_entry_point('mdtraj==0.9.1', 'console_scripts', 'mdinspect')()
  File "/home/kyleb/opt/lib/python2.7/site-packages/mdtraj-0.9.1-py2.7-linux-x86_64.egg/mdtraj/scripts/mdinspect.py", line 210, in entry_point
    main(args, parser)
  File "/home/kyleb/opt/lib/python2.7/site-packages/mdtraj-0.9.1-py2.7-linux-x86_64.egg/mdtraj/scripts/mdinspect.py", line 84, in main
    inspector.load_trajectory(f)
  File "/home/kyleb/opt/lib/python2.7/site-packages/mdtraj-0.9.1-py2.7-linux-x86_64.egg/mdtraj/scripts/mdinspect.py", line 112, in load_trajectory
    self.check_nonbonded()
  File "/home/kyleb/opt/lib/python2.7/site-packages/mdtraj-0.9.1-py2.7-linux-x86_64.egg/mdtraj/scripts/mdinspect.py", line 188, in check_nonbonded
    dist = spatial.distance_matrix(self.t.xyz[i], self.t.xyz[i])
  File "/home/kyleb/opt/lib/python2.7/site-packages/scipy/spatial/kdtree.py", line 958, in distance_matrix
    result = np.empty((m,n),dtype=np.float)  # FIXME: figure out the best dtype
MemoryError
```

This trajectory isn't actually that big:

```
In [3]: t
Out[3]: <mdtraj.Trajectory with 13 frames, 55678 atoms, 17451 residues, and unitcells at 0x7fac62628090>
```

**Comment by rmcgibbo** [comment]
It should probably use `compute_neighbors` instead. I'm not sure if anyone has really looked at that script in a while.
