### ISSUE TITLE
PSF Test Failure against VMD

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#682]
```
$ nosetests mdtraj.tests.test_psf
...EE
======================================================================
ERROR: mdtraj.tests.test_psf.test_vmd_psf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rmcgibbo/miniconda/envs/2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/rmcgibbo/miniconda/envs/2.7.9/lib/python2.7/site-packages/mdtraj-1.2.X-py2.7-macosx-10.5-x86_64.egg/mdtraj/tests/test_psf.py", line 52, in <lambda>
    yield lambda: _test_against_vmd(get_fn('1vii.pdb'))
  File "/Users/rmcgibbo/miniconda/envs/2.7.9/lib/python2.7/site-packages/mdtraj-1.2.X-py2.7-macosx-10.5-x86_64.egg/mdtraj/tests/test_psf.py", line 64, in _test_against_vmd
    top = top_paths[0]
IndexError: list index out of range

======================================================================
ERROR: mdtraj.tests.test_psf.test_vmd_psf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rmcgibbo/miniconda/envs/2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/rmcgibbo/miniconda/envs/2.7.9/lib/python2.7/site-packages/mdtraj-1.2.X-py2.7-macosx-10.5-x86_64.egg/mdtraj/tests/test_psf.py", line 53, in <lambda>
    yield lambda: _test_against_vmd(get_fn('2EQQ.pdb'))
  File "/Users/rmcgibbo/miniconda/envs/2.7.9/lib/python2.7/site-packages/mdtraj-1.2.X-py2.7-macosx-10.5-x86_64.egg/mdtraj/tests/test_psf.py", line 64, in _test_against_vmd
    top = top_paths[0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 5 tests in 1.169s

FAILED (errors=2)
```

Observed on OS X 10.10 w/ `VMD for MACOSXX86, version 1.9.2beta1 (September 12, 2014)`, both python 2.7 and 3.4

**Comment by kyleabeauchamp** [comment]
This is nothing new, but I did a quick test on my Ubuntu 14.04 desktop, 2.7 and 3.4 looks OK there.

**Comment by rmcgibbo** [comment]
Do you have a different version of VMD?

**Comment by kyleabeauchamp** [comment]
```
Info) VMD for LINUXAMD64, version 1.9.1 (February 1, 2012)
```

**Comment by rmcgibbo** [comment]
Oh, I see the issue.
