### ISSUE TITLE
Windows Errors (py27 only)

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#701]
In #698, I got more tests running on appveyor, including windows-32 and windows-64.

There are a couple errors.

Py27 / Win-32:

```
======================================================================
ERROR: mdtraj.tests.test_mdcrd.test_read_0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\tests\test_mdcrd.py", line 41, in test_read_0
    xyz, box = f.read()
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
 
ERROR: mdtraj.tests.test_mdcrd.test_read_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\tests\test_mdcrd.py", line 51, in test_read_1
    xyz, _ = f.read()
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_mdcrd.test_multiread
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\tests\test_mdcrd.py", line 90, in test_multiread
    reference = md.load(get_fn('frame0.mdcrd'), top=get_fn('native.pdb'))
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\core\trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 100, in load_mdcrd
    xyz, cell_lengths = f.read(stride=stride, atom_indices=atom_indices)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_mdcrd.test_seek
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\tests\test_mdcrd.py", line 99, in test_seek
    reference = md.load(get_fn('frame0.mdcrd'), top=get_fn('native.pdb'))
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\core\trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 100, in load_mdcrd
    xyz, cell_lengths = f.read(stride=stride, atom_indices=atom_indices)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_mdcrd.test_atom_indices_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\tests\test_mdcrd.py", line 132, in test_atom_indices_1
    t0 = md.load(get_fn('frame0.mdcrd'), top=top)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\core\trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 100, in load_mdcrd
    xyz, cell_lengths = f.read(stride=stride, atom_indices=atom_indices)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_trajectory.test_seek_read_mode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\tests\test_trajectory.py", line 398, in test_seek_read_mode
    xyz = md.load(get_fn(b), top=get_fn('native.pdb')).xyz
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\core\trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 100, in load_mdcrd
    xyz, cell_lengths = f.read(stride=stride, atom_indices=atom_indices)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_trajectory.test_load_frame
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\tests\test_trajectory.py", line 447, in test_load_frame
    trajectories = [md.load(get_fn(f), top=get_fn('native.pdb')) for f in files]
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\core\trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 100, in load_mdcrd
    xyz, cell_lengths = f.read(stride=stride, atom_indices=atom_indices)
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_32\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win32.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
----------------------------------------------------------------------
Ran 1047 tests in 752.966s
 
FAILED (SKIP=24, errors=7)
```

**Comment by rmcgibbo** [comment]
Py27 / Win-64
```
======================================================================
ERROR: mdtraj.tests.test_mdcrd.test_read_0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_mdcrd.py", line 41, in test_read_0
    xyz, box = f.read()
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_mdcrd.test_read_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_mdcrd.py", line 51, in test_read_1
    xyz, _ = f.read()
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_mdcrd.test_multiread
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_mdcrd.py", line 90, in test_multiread
    reference = md.load(get_fn('frame0.mdcrd'), top=get_fn('native.pdb'))
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\core\trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 100, in load_mdcrd
    xyz, cell_lengths = f.read(stride=stride, atom_indices=atom_indices)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_mdcrd.test_seek
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_mdcrd.py", line 99, in test_seek
    reference = md.load(get_fn('frame0.mdcrd'), top=get_fn('native.pdb'))
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\core\trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 100, in load_mdcrd
    xyz, cell_lengths = f.read(stride=stride, atom_indices=atom_indices)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_mdcrd.test_atom_indices_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_mdcrd.py", line 132, in test_atom_indices_1
    t0 = md.load(get_fn('frame0.mdcrd'), top=top)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\core\trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 100, in load_mdcrd
    xyz, cell_lengths = f.read(stride=stride, atom_indices=atom_indices)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_trajectory.test_seek_read_mode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_trajectory.py", line 398, in test_seek_read_mode
    xyz = md.load(get_fn(b), top=get_fn('native.pdb')).xyz
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\core\trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 100, in load_mdcrd
    xyz, cell_lengths = f.read(stride=stride, atom_indices=atom_indices)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
ERROR: mdtraj.tests.test_trajectory.test_load_frame
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_trajectory.py", line 447, in test_load_frame
    trajectories = [md.load(get_fn(f), top=get_fn('native.pdb')) for f in files]
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\core\trajectory.py", line 362, in load
    value = loader(filename, **kwargs)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 100, in load_mdcrd
    xyz, cell_lengths = f.read(stride=stride, atom_indices=atom_indices)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 251, in read
    coord, box = self._read()
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\mdcrd.py", line 307, in _read
    'encountered. ' % self._n_atoms)
IOError: mdcrd parse error: specified n_atoms (22) is likely incorrect. Incorrect buffer size encountered. 
 
======================================================================
FAIL: mdtraj.formats.pdb.tests.test_pdb.test_load_multiframe
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\pdb\tests\test_pdb.py", line 69, in <lambda>
    yield lambda: eq(t.n_frames, 2)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 
======================================================================
FAIL: mdtraj.formats.pdb.tests.test_pdb.test_load_multiframe
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\pdb\tests\test_pdb.py", line 70, in <lambda>
    yield lambda: eq(t.n_atoms, 22)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 
======================================================================
FAIL: mdtraj.formats.pdb.tests.test_pdb.test_4K6Q
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\pdb\tests\test_pdb.py", line 76, in test_4K6Q
    eq(t.n_frames, 1)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 
======================================================================
FAIL: mdtraj.formats.pdb.tests.test_pdb.test_2EQQ_0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\pdb\tests\test_pdb.py", line 101, in <lambda>
    yield lambda: eq(t.n_frames, 20)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 
======================================================================
FAIL: mdtraj.formats.pdb.tests.test_pdb.test_2EQQ_0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\pdb\tests\test_pdb.py", line 102, in <lambda>
    yield lambda: eq(t.n_atoms, 423)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 
======================================================================
FAIL: mdtraj.formats.pdb.tests.test_pdb.test_pdb_from_url
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\pdb\tests\test_pdb.py", line 184, in test_pdb_from_url
    eq(t1.n_frames, 1)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 
======================================================================
FAIL: mdtraj.formats.pdb.tests.test_pdb.test_1vii_url_and_gz
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\formats\pdb\tests\test_pdb.py", line 229, in test_1vii_url_and_gz
    eq(t1.n_frames, 1)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 
======================================================================
FAIL: mdtraj.tests.test_netcdf.test_read_after_close
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_netcdf.py", line 48, in <lambda>
    yield lambda: eq(f.n_frames, 101)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 
======================================================================
FAIL: mdtraj.tests.test_trajectory.test_restrict_atoms
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_trajectory.py", line 259, in test_restrict_atoms
    eq(traj.xyz.shape[1], 4)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 
======================================================================
FAIL: mdtraj.tests.test_trajectory.test_restrict_atoms_not_inplace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_trajectory.py", line 283, in test_restrict_atoms_not_inplace
    eq(sliced.xyz.shape[1], 4)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 
======================================================================
FAIL: mdtraj.tests.test_trajectory.test_stack_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_trajectory.py", line 366, in test_stack_1
    eq(t2.topology._numAtoms, 2*t1.n_atoms)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'int'> <type 'long'>
 
======================================================================
FAIL: mdtraj.tests.test_trajectory.test_stack_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\tests\test_trajectory.py", line 378, in test_stack_2
    eq(t3.n_atoms, 11)
  File "c:\python27_64\envs\_test\lib\site-packages\mdtraj-1.3.0.dev0-py2.7-win-amd64.egg\mdtraj\testing\testing.py", line 133, in eq
    assert (type(o1) is type(o2)), 'o1 and o2 not the same type: %s %s' % (type(o1), type(o2))
AssertionError: o1 and o2 not the same type: <type 'long'> <type 'int'>
 ```

**Comment by rmcgibbo** [comment]
Looks like the mdcrd issue is py2 vs py3. Old windows tests were only running with py3, and thats where its working.
