### ISSUE TITLE
Question about writing a PDB file

### ISSUE THREAD

**Issue by acadev** [mdtraj/mdtraj#767]
Hi, I had a question about writing PDB files after clustering using KMeans algorithm. I just started using mdtraj - so my questions may be somewhat naive, but when I run this snippet I get the error listed below:

```
from msmbuilder.cluster import KMeans
k  = 10; # number of clusters

clusterer = KMeans(n_clusters=k);
clusterer.fit(PHI);
labels = {};
labels['IDR1.dcd'] = clusterer.labels_[0];
labels['IDR2.dcd'] = clusterer.labels_[1];

for i in range(0, k):
        for trajFile in ['IDR1.dcd', 'IDR2.dcd']:
                t = md.load(trajFile, top='IDR2.pdb');
                targets = t[np.where(labels[trajFile] == i)];
                print targets.topology;
                if len(targets) >0:
                        rmsds = md.rmsd(targets[1:], targets[0]);
                        print i, len(targets), np.mean(rmsds), np.std(rmsds); #print the statistics about the clusters
                with md.formats.PDBTrajectoryFile('target_' + str(i) + '.pdb', 'w') as f:
                        for frame in targets:
                                print frame;
                                f.write(frame, targets.topology, modelIndex=1);
```
The error I get is as follows:
```
<mdtraj.Topology with 1 chains, 31 residues, 503 atoms, 503 bonds>
<mdtraj.Topology with 1 chains, 31 residues, 503 atoms, 503 bonds>
0 13459 0.448458 0.100244
<mdtraj.Trajectory with 1 frames, 503 atoms, 31 residues, and unitcells>
Traceback (most recent call last):
  File "createDatasets.py", line 40, in <module>
    f.write(frame, targets.topology, modelIndex=1); 
  File "/Users/v33/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/mdtraj-1.2.0-py2.7-macosx-10.6-x86_64.egg/mdtraj/formats/pdb/pdbfile.py", line 274, in write
    raise ValueError('The number of positions must match the number of atoms')
ValueError: The number of positions must match the number of atoms
```
I am using the same topology and I am not sure where I am making a mistake. 

Thank you once again for all the help.

**Comment by mpharrigan** [comment]
Try 
```
targets.save("target_{}.pdb".format(i))
```

**Comment by mpharrigan** [comment]
In place of the for loop

**Comment by acadev** [comment]
Thank you! It worked well.
