### ISSUE TITLE
HDF5Reporter fails with virtual sites

### ISSUE THREAD

**Issue by zonca** [mdtraj/mdtraj#827]
I am using `tip5p` water model in OpenMM that has 2 virtual sites M1 and M2 in each water molecule.

HDF5Reporter tries to save the topology, however it needs the `element` field of an atom, however this is not available in virtual sites. See error log below.

I worked around this using `atomSubset`:

```
simulation.reporters.append(HDF5Reporter('output.h5', 10, atomSubset=[a.index for a in pdb.topology.atoms() if not a.name.startswith("M")]))
```

however I was wondering if it would be useful to automatically discard virtual sites.

```
Traceback (most recent call last):
  File "test_reporters.py", line 48, in <module>
    simulation.step(100)
  File "/home/zonca/anaconda/lib/python3.4/site-packages/simtk/openmm/app/simulation.py", line 127, in step
    reporter.report(self, state)
  File "/home/zonca/anaconda/lib/python3.4/site-packages/mdtraj-1.3.0-py3.4-linux-x86_64.egg/mdtraj/reporters/basereporter.py", line 208, in report
    self._initialize(simulation)
  File "/home/zonca/anaconda/lib/python3.4/site-packages/mdtraj-1.3.0-py3.4-linux-x86_64.egg/mdtraj/reporters/basereporter.py", line 160, in _initialize
    self._traj_file.topology = simulation.topology
  File "/home/zonca/anaconda/lib/python3.4/site-packages/mdtraj-1.3.0-py3.4-linux-x86_64.egg/mdtraj/formats/hdf5.py", line 87, in wrapper
    return f(*args, **kwargs)
  File "/home/zonca/anaconda/lib/python3.4/site-packages/mdtraj-1.3.0-py3.4-linux-x86_64.egg/mdtraj/formats/hdf5.py", line 360, in topology
    topology_object = Topology.from_openmm(topology_object)
  File "/home/zonca/anaconda/lib/python3.4/site-packages/mdtraj-1.3.0-py3.4-linux-x86_64.egg/mdtraj/core/topology.py", line 324, in from_openmm
    a = out.add_atom(atom.name, elem.get_by_symbol(atom.element.symbol), r)
AttributeError: 'NoneType' object has no attribute 'symbol'
```

**Comment by rmcgibbo** [comment]
Do you think we want to discard them, or should we actually be saving them too?

**Comment by zonca** [comment]
The other OpenMM reporters, e.g. `PDBReporter`,  write them, so better write them as well.

**Comment by NickWton** [comment]
I've noticed that virtual sites also fail for some analysis modules, such as "baker_hubbard" due to the same error, which can be traced to mdtraj\geometry\hbond:284 as such, 
```
acceptors = [a.index for a in traj.topology.atoms if a.element.symbol == 'O' or a.element.symbol == 'N']
```
this fails because virtual sites don't have elements (NoneType), and thus do not have symbols, so that throws the same error. One work around I noticed would be to switch the line to:
 ```
acceptors = [a.index for a in traj.topology.atoms if str(a.element) == 'oxygen' or str(a.element) == 'nitrogen']
```
Not sure if that's the ideal fix though.

**Comment by swails** [comment]
I vote for creating a massless `virtual` `Element` with an atomic number of 0.

This is an API breakage, though, as all tests for virtual sites would need to be changed from `atom.element is None` to `atom.element is virtual`.  An alternative to this is to take advantage of short-circuiting and just add `if atom.element is not None and (atom.element.symbol == 'O' or atom.element.symbol == 'H')`...

A quick grep of where `element` is assumed to have an attribute yields a large number of places where this is true:

```
[swails@Robin ~/src/mdtraj/mdtraj (virtualsites) ]$ grep "element\." `find . -name "*.py"`
./core/element.py:element.py: Used for managing elements.
./core/element.py:    """An Element represents a chemical element.
./core/element.py:    such as element.hydrogen or element.carbon.  You can also call the static method
./core/element.py:            if mass < other_element.mass:
./core/element.py:                # since it's the "canonical" element.
./core/element.py:            massdiff = abs(element.mass - mass)
./core/selection.py:        # Atom.element.<attribute>
./core/selection.py:    '(atom.residue.is_protein and (atom.element.symbol == CA))'
./core/topology.py:                    a = out.addAtom(atom.name, app.Element.getBySymbol(atom.element.symbol), r)
./core/topology.py:                    a = out.add_atom(atom.name, elem.get_by_symbol(atom.element.symbol), r)
./core/topology.py:                element_symbol = atom.element.symbol
./core/topology.py:        element : mdtraj.element.Element
./core/topology.py:    element : mdtraj.element.Element
./core/topology.py:        if self.element.name != other.element.name:
./formats/arc.py:                # First get the element. Try for common 2-letter elements, then
./formats/hdf5.py:                            element_symbol_string = str(atom.element.symbol)
./formats/mol2.py:    if atoms_mdtraj.element.isnull().any():
./formats/pdb/pdbfile.py:                    if len(atom.name) < 4 and atom.name[:1].isalpha() and (atom.element is None or len(atom.element.symbol) < 2):
./formats/pdb/pdbfile.py:                        symbol = atom.element.symbol
./formats/pdb/pdbstructure.py:            self.element = element.get_by_symbol(self.element_symbol)
./formats/pdb/pdbstructure.py:                    self.element = element.hydrogen
./formats/pdb/pdbstructure.py:                    self.element = element.get_by_symbol(symbol)
./formats/pdb/tests/test_element.py:    H = element.Element.getBySymbol('H')
./formats/pdb/tests/test_element.py:    eq(a.element, element.hydrogen)
./formats/pdb/tests/test_pdb.py:    eq(atom.element.symbol, 'O')
./geometry/contact.py:            residue_membership = [[atom.index for atom in residue.atoms if not (atom.element == element.hydrogen)]
./geometry/distance.py:    masses = np.array([a.element.mass for a in traj.top.atoms])
./geometry/hbond.py:        atoms = [(b[0], b[1]) for b in bonditer if set((b[0].element.symbol, b[1].element.symbol)) == elems]
./geometry/hbond.py:            if a0.element.symbol == e1:
./geometry/hbond.py:        acceptors = [a.index for a in traj.topology.atoms if a.element.symbol == 'O' or a.element.symbol == 'N']
./geometry/hbond.py:        acceptors = [a.index for a in traj.topology.atoms if (a.element.symbol == 'O' and a.residue.name != 'HOH') or a.element.symbol == 'N']
./geometry/hbond.py:        atoms = [(b[0], b[1]) for b in bonditer if set((b[0].element.symbol, b[1].element.symbol)) == elems]
./geometry/hbond.py:            if a0.element.symbol == e1:
./geometry/hbond.py:        acceptors = [a.index for a in traj.topology.atoms if a.element.symbol == 'O' or a.element.symbol == 'N']
./geometry/hbond.py:        acceptors = [a.index for a in traj.topology.atoms if (a.element.symbol == 'O' and a.residue.name != 'HOH') or a.element.symbol == 'N']
./geometry/order.py:    masses = np.array([atom.element.mass for atom in traj.top.atoms])
./geometry/order.py:    masses = np.array([atom.element.mass for atom in traj.top.atoms])
```

In particular, the listcomps will be tricky to get to work correctly when virtual sites are `None` (at least as list comps).

I submitted a PR #835 that is a template for what I mean here.

**Comment by rmcgibbo** [comment]
#835 was just merged. @zonca can you try with the latest master branch?
