### ISSUE TITLE
Tables import fails?

### ISSUE THREAD

**Issue by davidlmobley** [mdtraj/mdtraj#852]
We're suddenly getting a peculiar error relating to an unknown module `tables` in a delayed import in openmoltools which seems related to mdtraj: https://travis-ci.org/choderalab/openmoltools/jobs/65974464#L1052-L1053

Key lines:

```
The code at io.py:88 requires the python module PyTables,
which is a package for managing hierarchical datasets and designed to
efficiently and easily cope with extremely large amounts of data.
PyTables can be downloaded from http://www.pytables.org, or installed with
the python "easy_install" or "pip" package managers using:
# easy_install tables
or
# pip install tables
PyTables also depends on the numexpr package, as well as the C-language
HDF5 library. For detailed installation instructions, visit
http://pytables.github.io/usersguide/installation.html
##########################################################################
Traceback (most recent call last):
  File "/home/travis/miniconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import openmoltools
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/openmoltools-0.6.8.dev0-py2.7.egg/openmoltools/__init__.py", line 28, in <module>
    from openmoltools import amber_parser, system_checker, utils, packmol, openeye, amber, cirpy, gromacs
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/openmoltools-0.6.8.dev0-py2.7.egg/openmoltools/amber_parser.py", line 9, in <module>
    import mdtraj as md
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/mdtraj/__init__.py", line 29, in <module>
    from mdtraj.formats.registry import _FormatRegistry
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/mdtraj/formats/__init__.py", line 8, in <module>
    from mdtraj.formats.pdb import PDBTrajectoryFile
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/mdtraj/formats/pdb/__init__.py", line 24, in <module>
    from mdtraj.formats.pdb.pdbfile import PDBTrajectoryFile, load_pdb
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/mdtraj/formats/pdb/pdbfile.py", line 54, in <module>
    from mdtraj.io import open_maybe_zipped
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/mdtraj/io.py", line 88, in <module>
    tables = import_('tables')
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/mdtraj/utils/delay_import.py", line 194, in import_
    raise e
ImportError: No module named tables
TESTS FAILED: openmoltools-dev-py27_0
```

It's possible this is a result of something on our end in openmoltools, but we haven't changed anything in this regard and this seems to have *just* broken. Maybe it's a recipe issue?

**Comment by rmcgibbo** [comment]
This is actually kind of subtle bug in MDTraj 1.4.0 (just released) -- thanks for reporting. I will think about a fix. One fix is just to add tables as a mandatory dependency, or tweak the imports a bit.

If you need this fixed immediately to keep up the momentum on `opemoltools` (it's going to take me a little while to fix this and make either a new release or new conda binaries), you can add `tables` as a dependency of `opemoltools` in your `devtools/conda-recipe/meta.yaml`.

**Comment by davidlmobley** [comment]
@jchodera, @kyleabeauchamp - any preferences with respect to how we deal with this in `openmoltools`? Add `tables` as a mandatory dependency?

**Comment by kyleabeauchamp** [comment]
I'm fine with that for now.  Pytables is part of anaconda and we already use it for some other projects, so I don't see a huge burden with one extra requirement.

**Comment by jchodera** [comment]
We can just add `pytables` to `openmoltools` dependencies for now.

**Comment by rmcgibbo** [comment]
Should be fixed now.
