### ISSUE TITLE
Support for gromacs residue names

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#892]
It appears that gromacs residue names can be longer than three characters.  See [this example](https://gist.github.com/jchodera/16f425f9fa84d9587253).

In this case, the small molecule is named `p-xylene` in the OpenMM `Topology` object when using the `simtk.openmm.app` gromacs loaders:
```
       0 'p-xylene'
       1 'HOH'
       2 'HOH'
       3 'HOH'
       4 'HOH'
       5 'HOH'
       6 'HOH'
...
```
When using the mdtraj DSL to try to select these with `resname p-xylene`, the following error is generated:
```
Traceback (most recent call last):
  File "/Users/choderaj/anaconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/cli.py", line 102, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/commands/prepare.py", line 39, in dispatch
    return dispatch_binding(args)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/commands/prepare.py", line 413, in dispatch_binding
    [phases, systems, positions, atom_indices] = setup_binding_gromacs(args)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/commands/prepare.py", line 355, in setup_binding_gromacs
    atom_indices[phase] = find_components(top.topology, ligand_dsl)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/commands/prepare.py", line 105, in find_components
    atom_indices['ligand'] = mdtraj_top.select(ligand_dsl).tolist()
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/mdtraj/core/topology.py", line 847, in select
    filter_func = parse_selection(selection_string).expr
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/mdtraj/core/selection.py", line 352, in __call__
    raise ValueError('\n'.join(lines))
ValueError: Expected end of text (at char 9), (line:1, col:10): resname p-xylene
                                                                         ^^^
```

**Comment by mpharrigan** [comment]
Did you try putting it in quotes? it looks like it doesn't like the hyphen.

You can also use the list comprehension form, especially if this is going to be buried in a library and not user-facing.

```python
[a.index for a in top.atoms if a.residue.name == 'p-xylene']
```

**Comment by jchodera** [comment]
> Did you try putting it in quotes? it looks like it doesn't like the hyphen.

Specifying single quotes (`'p-xylene'`) in the DSL worked!

> You can also use the list comprehension form, especially if this is going to be buried in a library and not user-facing.

We're trying to support the DSL, so it is user-facing.

Thanks!
