### ISSUE TITLE
Preferred idiom for writing trajectories without loading entire trajectory into memory?

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#929]
What's the preferred idiom for writing trajectories without first loading the entire trajectory into memory?

I was a bit surprised that the approach of calling `write()` multiple times doesn't seem to yield readable trajectories:
```
with mdtraj.formats.XTCTrajectoryFile(output_filename, mode='w') as f:
   for frame in range(nframes):
      f.write(source.getFrame(frame))
```
instead produces errors like this when read:
```
Traceback (most recent call last):
  File "analyze-yank-with-xtram.py", line 78, in <module>
    coordinates_source = pyemma.coordinates.source(trajectory_filenames, features=featurizer)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/pyEMMA-2.0.1-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/api.py", line 347, in source
    reader = _create_file_reader(inp, top, features, chunk_size=chunk_size if chunk_size else 100)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/pyEMMA-2.0.1-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/data/util/reader_utils.py", line 92, in create_file_reader
    chunksize=chunk_size)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/pyEMMA-2.0.1-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/data/feature_reader.py", line 98, in __init__
    self._assert_toptraj_consistency()
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/pyEMMA-2.0.1-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/data/feature_reader.py", line 267, in _assert_toptraj_consistency
    traj = mdtraj.load_frame(self.trajfiles[0], index=0, top=self.topfile)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 291, in load_frame
    return loader(filename, frame=index, **kwargs)
  File "xtc.pyx", line 133, in xtc.load_xtc (mdtraj/formats/xtc/xtc.c:2116)
  File "xtc.pyx", line 140, in xtc.load_xtc (mdtraj/formats/xtc/xtc.c:2071)
  File "xtc.pyx", line 310, in xtc.XTCTrajectoryFile.read_as_traj (mdtraj/formats/xtc/xtc.c:3816)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 1074, in __init__
    self.xyz = xyz
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 823, in xyz
    warn_on_cast=False, add_newaxis_on_deficient_ndim=True)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/mdtraj/utils/validation.py", line 148, in ensure_type
    raise error
ValueError: xyz must be shape (Any, 3238, 3). You supplied  (1, 3424, 3)
```
Am I missing something?  Should the simple idiom of calling `write` multiple times work just fine?

**Comment by jchodera** [comment]
Hm.  I get this error even when writing whole trajectories at once.  The issue must lie elsewhere.

**Comment by rmcgibbo** [comment]
The issue is the number of atoms in the trajectory and topology not matching up.

**Comment by jchodera** [comment]
Just figured that out---thanks, and sorry!

**Comment by MaryamSSadeghi** [comment]
Hi, I cannot find the issue related to this warning:

python pycgtool.py -g ref.gro -x md2.xtc -m PCL10.map -b PCL10.bnd
Using GRO: ref.gro
Using XTC: md2.xtc

WARNING: Using MDTraj which renames solvent molecules
Traceback (most recent call last):
  File "/home/maryam/Desktop/CG-PCL10/pycgtool/framereader.py", line 34, in get_frame_reader
    return readers[name](top, traj, frame_start)
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pycgtool.py", line 65, in <module>
    main(args, config)
  File "/home/maryam/Desktop/CG-PCL10/pycgtool/pycgtool.py", line 21, in main
    frame = Frame(gro=args.gro, xtc=args.xtc, itp=args.itp, frame_start=args.begin)
  File "/home/maryam/Desktop/CG-PCL10/pycgtool/frame.py", line 135, in __init__
    self._trajreader = get_frame_reader(gro, traj=xtc, frame_start=frame_start)
  File "/home/maryam/Desktop/CG-PCL10/pycgtool/framereader.py", line 41, in get_frame_reader
    return reader(top, traj, frame_start)
  File "/home/maryam/Desktop/CG-PCL10/pycgtool/framereader.py", line 202, in __init__
    self._traj = mdtraj.load(trajname, top=topname)
  File "/home/maryam/anaconda3/lib/python3.6/site-packages/mdtraj/core/trajectory.py", line 430, in load
    value = loader(filename, **kwargs)
  File "mdtraj/formats/xtc/xtc.pyx", line 165, in xtc.load_xtc (mdtraj/formats/xtc/xtc.c:2766)
  File "mdtraj/formats/xtc/xtc.pyx", line 172, in xtc.load_xtc (mdtraj/formats/xtc/xtc.c:2720)
  File "mdtraj/formats/xtc/xtc.pyx", line 336, in xtc.XTCTrajectoryFile.read_as_traj (mdtraj/formats/xtc/xtc.c:4579)
  File "mdtraj/formats/xtc/xtc.pyx", line 407, in xtc.XTCTrajectoryFile.read (mdtraj/formats/xtc/xtc.c:5612)
  File "mdtraj/formats/xtc/xtc.pyx", line 446, in xtc.XTCTrajectoryFile._read (mdtraj/formats/xtc/xtc.c:6959)
MemoryError
