### ISSUE TITLE
Atom selection error message

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#936]
When you use an incorrect syntax with a keyword that doesn't exist, the atom select function can go a little crazy.

```
$ python -c 'import mdtraj as md; t = md.load("bpti-100.pdb"); t.top.select("nonexistantqualifier O")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/mdtraj-1.4.2-py3.4-linux-x86_64.egg/mdtraj/core/topology.py", line 926, in select
    filter_func = parse_selection(selection_string).expr
  File "/home/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/mdtraj-1.4.2-py3.4-linux-x86_64.egg/mdtraj/core/selection.py", line 348, in __call__
    parse_result = self.expression.parseString(selection, parseAll=True)
  File "/home/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/mdtraj-1.4.2-py3.4-linux-x86_64.egg/mdtraj/utils/external/pyparsing.py", line 1101, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/mdtraj-1.4.2-py3.4-linux-x86_64.egg/mdtraj/utils/external/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
[... snip; it keeps going on like this for pages...]
```

**Comment by mpharrigan** [comment]
This is a pyparsing thing, no? We should check if they've fixed / made improvements upstream since we just copied it into the source tree

**Comment by rmcgibbo** [comment]
I think so. We could just catch the error and rethrow it as something reasonable.

**Comment by mpharrigan** [comment]
We already do that a little bit

https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/selection.py#L349

**Comment by rmcgibbo** [comment]
here's the full traceback https://gist.github.com/rmcgibbo/48346bd9100de83a526b. the message at the end is probably reasonable

**Comment by mpharrigan** [comment]
So really the stack trace is just too deep

**Comment by rmcgibbo** [comment]
pretty much
